### ISSUE TITLE
How should start, end, and size of insertions be compared?

### ISSUE THREAD

**Issue by jzook** [fritzsedlazeck/SURVIVOR#1]
As we discussed during the hackathon, insertions are represented in many different ways by different callers, particularly in how the end and size of the insertion is represented.  It would be great to find a way to compare these appropriately.

**Comment by fritzsedlazeck** [comment]
Hi, yes. The only thought that I had so far is to just compare the start breakpoints. Those should be the same for every caller. What do you think?

**Comment by jzook** [comment]
Yes, I was also thinking that could be a good first step.  The other thing
that would be great to do (perhaps later) would be to add the length for
the callsets that have size information.  Unfortunately, this is output in
different ways by different callers, and not at all by some callers, but
it'll be really useful for integration.  Long-term, it'd be great to keep
the actual inserted sequence when it is output by the callers, but again,
this is done in different ways by different callers, and not at all by some.

**Comment by fritzsedlazeck** [comment]
I have now implemented in that way that SURVIVOR sees the start and end coordinates as the region where the insertions occurs and the SVLEN= gives the size. In best case start == end+1. 
I have also added a function that converts existing insert calls to this format if they report the end coordinate including the length of the insertion.
