### ISSUE TITLE
SURVIVOR 10 issue

### ISSUE THREAD

**Issue by MeHelmy** [fritzsedlazeck/SURVIVOR#10]
using `./SURVIVOR 10 ./test.tails 20 test.vcf`

The input is:

```
#id	chrKey	uRef	uBreak	uMapq	dRef	dBreak	dMapq	remainSeq	annot	numReads	numZMWs	evidence
0	1_1	1	40015898	254	1	40030111	254	1	DEL	2	2	->p=i->;<-i=p<-
```
The output:

```
1	40015898	DEL00Honey	N	<DEL>	.	LowQual	IMPRECISE;SVTYPE=DEL;SVMETHOD=Honey_tails;CHR2=1;END=40030111;SVLEN=14213;PE=1	GT:GL:GQ:FT:RC:DR:DV:RR:RV
```

Is this value `DEL00Honey` is the default behavior?

also the coverage is not included, what is PE filed why it is always 1?

Thanks,

**Comment by fritzsedlazeck** [comment]
Hi,
DEL00Honey is just for the id. If you want I can make it increasing. 
Yes, I only focused on the coordinates and type since these are the values that I needed. If you need it I can add the increase in ID as well as the transfer of num of reads. 
Cheers
Fritz
