### ISSUE TITLE
Question about merge behavior

### ISSUE THREAD

**Issue by gbdias** [fritzsedlazeck/SURVIVOR#101]
> SURVIVOR 1.0.6 from Bioconda

Hi Fritz,

I have a few questions about the behavior of `SURVIVOR merge`.
Assuming I have three VCF files, A, B and C:
![venn-01](https://user-images.githubusercontent.com/7614153/66596347-b9eeb380-eb6a-11e9-9642-3e8748780d4c.png)

1.  If I understand the binary representation correctly, when I run `SURVIVOR merge` **without** a minimum SV length filter (as shown in the command below), I should be able to match the number of SVs in my original A.vcf file by adding up the number of SVs with `SUPP_VEC=` 100+110+101+111.
```
SURVIVOR merge list_of_vcfs.txt 1000 1 1 1 0 0 merged_1kb.vcf
```
   - However, when I sum `SUPP_VEC=` 100+110+101+111, I always get fewer SVs than there were in my original A.vcf (same for all vcfs). Is SURVIVOR filtering some SVs out?

________________________

2. How does the maximum distance parameter works? I assume that as I increase the maximum allowed distance, more SVs get merged, and vice versa. However, in my test data it looks like the number of SVs shared/merged by at least two samples (`SUPP_VEC=`111/110/011/101) sometimes decreases as I increase merging distance:

Merge distance (bp) | \# of shared SVs
-- | --
100 | 280
200 | 285
300 | 285
500 | 288
1000 | 280

**Comment by fritzsedlazeck** [comment]
Thanks for this nice report.
SURVIVOR has two merges going on. First, it merges close by SVs within the same sample. This is to cope better with noisy alignments/ tricky regions. 
Second, it merges across the samples. 
I hope that this helps.
Thanks
Fritz

**Comment by gbdias** [comment]
Thanks for the clarification Fritz.
- About the merging distance, could you imagine a case where increasing the maximum merging distance would result in fewer merged SVs rather than more?
- Also, do you have a recommendation of merge distance to use?

**Comment by fritzsedlazeck** [comment]
@1: Yes in very strange situations.. if there are multiple SVs next to each other eg. every 100bp. Then the grouping can lead to strange clustering behavior.

@2: We are always using 1kbp as the merge distance. Note that in the output VCF file it displays the distance used. Most of the time 50bp are enough but in repetitive/ low complex regions is where multiple 100bp are necessary. 

Thanks
fritz

**Comment by gbdias** [comment]
Got it.
Thanks for the help!
Gui

**Comment by Nazeeefa** [comment]
Hi,

I also have a question related to `merge` behaviour.  I have been doing some parameter testing, with different values for maximum distance allowed (0-500), to identify what amount and type of SVs in my long read data overlap with the [truth set](https://www.ncbi.nlm.nih.gov/dbvar/studies/nstd152/).

![survivor_testing_nf](https://user-images.githubusercontent.com/6730853/71122075-0e07bb00-21e0-11ea-8ff7-048912d6d65a.jpeg)

In my case, decreasing breaking distance increases the amount of merged SVs, while the amount of SVs (from all samples, I have two) that overlap/merged with truth set decreases. 

I am trying to figure out what breaking distance value is appropriate to detect overlap? In my naive view, given that I am working with long reads, I think second row/test could be a good indication (venn diagram attached). I appreciate anyone's help/guidance. Thank you.

![data_ts](https://user-images.githubusercontent.com/6730853/71122229-617a0900-21e0-11ea-869d-6cf62c72a9d8.png)

Cheers,
Nazeefa

**Comment by dKlee99** [comment]
@Nazeeefa Hi, May I ask how you managed to plot last venn diagram? I'm having troubles with plotting it. Please refer to #151 Thanks !
