### ISSUE TITLE
Using compressed files

### ISSUE THREAD

**Issue by oalavijeh** [fritzsedlazeck/SURVIVOR#102]
Dear Fritz, 

I have >20,000 individual compressed "structural VCFs" each representing a patient who has has Manta and Canvas called on their WGS data. Each VCF is gzipped and is a combination of all types of calls (DUP, DEL, INV, CNV etc). 

I would like to use SURVIVOR to merge these files, are vcf.gz files ok to use? Do the calls need to be divided out into separate files e.g. dups.vcf.gz, dels.vcf.gz or will SURVIVOR accept different calls in the same VCF? 

If VCFs are needed is there a workflow to turn zipped vcfs into vcfs for analysis? 

Many thanks for your time 

Omid

**Comment by fritzsedlazeck** [comment]
Hi Omid,
thanks for reaching out. We dont currently support .gz compressed vcf files. 
SURVIVOR handles multiple types in the VCF files. 

We did had a beta version to read in gz files, but there remains a bug in there....  I know its a limitation right now and we are working on it. 

Thanks
Fritz

**Comment by oalavijeh** [comment]
Ah thanks for that, may be worth mentioning as such in the introduction. I'll keep track of your tool (it looks really awesome!) and will definitely use it once compressed formats are supported. 

All the best

Omid

**Comment by stefanucci-luca** [comment]
Dear Fritz, 

Do you have any news about the possibility to work on vcf.gz files? I got stuck with this very problem.

Best,

Luca

**Comment by fritzsedlazeck** [comment]
Sorry the one library that I tested lead to errors. Are the VCF files too many / too large to be extracted?
Thanks
Fritz
