### ISSUE TITLE
Using merge on a single VCF 

### ISSUE THREAD

**Issue by oalavijeh** [fritzsedlazeck/SURVIVOR#104]
Dear Fritz, 

If one were to use the merge function on a single vcf would it compare and contrast within a single SV itself much the lsort function in SV-tools? If not, if one then split the single VCF file into two smaller files and ran merge on them would it work in a similar fashion?

Many thanks for your help

**Comment by fritzsedlazeck** [comment]
If you use it on a single vcf file svs will be collapse if they are close to each other but nothing else will happen.

If you split the file and do the same a similar thing will happen.
I hope that answers it.
Cheers
Fritz
