### ISSUE TITLE
confusion about SURVIVOR merge

### ISSUE THREAD

**Issue by AJ211** [fritzsedlazeck/SURVIVOR#106]
Hi Fritz,
     I have a question about the result getting from SURVIVOR merge.
     I do SURVIVOR merge for SV study in a population. What confused me is that I see the genotype with ./.  caused by two different ways, please see the example as below:
    1.    ./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN
    2.    ./.:NA:6490:0,0:--:.:INV:2175:NA:NA:chr1_20660694-chr1_20667184

 So what is the difference between the two examples above? I think they both means that the absence of the SV in specific sample, right? But why the second one can be viewed as one support in the SUPP_VEC as the DR (reference reads support) and DV (variant reads support) value are equal to zero?

**Comment by fritzsedlazeck** [comment]
./. means unknown, not necessarily absent that would be 0/0

@1: There is no variant in the sample that matches the initial SV
@2: There is a INV at this position for this sample, but the genotype was not set in the input VCF.

I hope that helps
Fritz
