### ISSUE TITLE
SURVIVOR filter Bionano vcf

### ISSUE THREAD

**Issue by MaestSi** [fritzsedlazeck/SURVIVOR#107]
Hi,
I am trying to filter a vcf file produced by Bionano solve pipeline, using `SURVIVOR filter`.
In particular, I'd like to filter for SV length, retaining only SVs bigger than 1kbp.
My command is the following:
`SURVIVOR filter input.vcf NA 1000 -1 0 -1 output.vcf`
However, in output.vcf file there are still some SVs with SVLEN smaller than 1kbp. My guess is that SURVIVOR filter is retrieving the END and POS values, and evaluating the difference between them, instead of retrieving SVLEN value. Could you please confirm this? If this is the case, is there an easy way to force SURVIVOR to filter using SVLEN instead of END-POS?
Thanks in advance,
Simone

**Comment by fritzsedlazeck** [comment]
Hey Simone,
SURVIVOR tries to use SVLEN if it finds it. Otherwise the stop - start. 
Can you send an example (fritz.sedlazeck@gmail.com ) 
Thanks
Fritz

**Comment by MaestSi** [comment]
Sure!
Simone

**Comment by fritzsedlazeck** [comment]
I pushed an update. Please try it out. 
Thanks
Fritz

**Comment by MaestSi** [comment]
Thank you very much Fritz, I confirm it works perfectly now.
Simone
