### ISSUE TITLE
Minor systematic bias on small deletions/insertions

### ISSUE THREAD

**Issue by ctsa** [fritzsedlazeck/SURVIVOR#11]
Hi @fritzsedlazeck ,

I've noticed survivor usage in some recent publications analyzes ins/del at sizes 50 and higher -- note that the manta default is actually off by one from this value. If you haven't reconfigured it, Manta results will be 51 bases and higher, per the configuration file setting here:

https://github.com/Illumina/manta/blob/c96587d1ebaba48d17d7144f2454972489e37f3f/src/python/bin/configManta.py.ini#L23

This will have a minor impact overall, but I think it's worth noting/correcting in future if this is not already configured in the SURVIVOR pipeline.

Thanks! -c

**Comment by fritzsedlazeck** [comment]
Hi Chris,
thanks for mentioning it. SURVIVOR does not have any information about which program was chosen as input, so I dont really have a chance to correct it. 
The threshold of 50bp was just taken to make everything comparable and means larger or equal 50bp. 
Thanks
Fritz

**Comment by ctsa** [comment]
Thanks, then it's an item to note for some recent SURVIVOR analyses only. If the input SV calling parameterization is not part of SURVIVOR itself then I'll close this as an item here.
