### ISSUE TITLE
SURVIVOR merge VCF output not found

### ISSUE THREAD

**Issue by MikeWLloyd** [fritzsedlazeck/SURVIVOR#113]
I've tired a number of different things, but can't find a way past this. 

I am trying to merge 2 VCF files, which both are the result of a prior `SURVIVOR merge` from 4 callers. I would like to assess the number of calls which overlap among the samples. 

```
SURVIVOR merge recesive_samples.txt 1000 1 1 0 0 0 VCF_OUTPUT
merging entries: 364485
merging entries: 474265
VCF Parser: could not open file:
```
I have tried different file names, different path statements etc., but nothing seems to work. Any ideas?

**Comment by fritzsedlazeck** [comment]
Please check if there is an empty line or so in your file. 
Thanks
Fritz

**Comment by MikeWLloyd** [comment]
@fritzsedlazeck that was it. I had a hidden extra line in recesive_samples.txt

**Comment by fritzsedlazeck** [comment]
No worries. Survivor prints the file that it cannot find... So was either space or empty line... Maybe I should build in a check. 
Thanks
Fritz
