### ISSUE TITLE
Coordinates of merged SVs

### ISSUE THREAD

**Issue by Madelinehazel** [fritzsedlazeck/SURVIVOR#116]
Hello, 

How are the POS and END coordinates chosen for merged SVs? I.e. if there are 4 calls supporting a deletion, all with slightly different start and end coordinates, how does SURVIVOR decide which is used for POS and END in the final VCF? 

Example: 

1 | 1866343 | DEL0086SUR | N | <DEL> | . | PASS | SUPP=4;SUPP_VEC=0000110101;AVGLEN=-628.75;SVTYPE=DEL;SVMETHOD=SURVIVORv2;CHR2=1;END=1866988;CIPOS=0,34;CIEND=-11,35;STRANDS=+- | GT:PSV:LN:DR:ST:TY:CO | ./.:NaN:0:0,0:--:NaN:NaN | ./.:NaN:0:0,0:--:NaN:NaN | ./.:NaN:0:0,0:--:NaN:NaN | ./.:NaN:0:0,0:--:NaN:NaN | 1/1:NA:607:0,60:+-:DEL:1_1866377-1_1866984 | 1/1:NA:661:125,122:+-:DEL:1_1866362-1_1867023 | ./.:NaN:0:0,0:--:NaN:NaN | 0/1:NA:645:0,10000:+-:DEL:1_1866343-1_1866988 | ./.:NaN:0:0,0:--:NaN:NaN | 2:0:NA:602:0,0:+-:DEL:1_1866376-1_1866977

Thanks

**Comment by fritzsedlazeck** [comment]
It sorts the start position and takes the call with the median start position as representative. 
Cheers
Fritz

**Comment by Madelinehazel** [comment]
Thanks for the quick reply!
