### ISSUE TITLE
SURVIVOR genComp outputs an empty matrix file

### ISSUE THREAD

**Issue by astulaaa** [fritzsedlazeck/SURVIVOR#117]
Hello,

I am using command SURVIVOR genComp sample_merged.vcf 0 sample_merged.mat.txt
The input "sample_merged.vcf" is not an empty file, it contains 489 lines. (generated with comand "SURVIVOR merge sample_files 0-20 2 1 0 0 20 sample_merged.vcf". What could have possibly went wrong?

**Comment by fritzsedlazeck** [comment]
Is there any error message ? Can you post a part of your VCF file?
Thanks
Fritz

**Comment by astulaaa** [comment]
After several attempts output was produced
probably server issue

Thank you
