### ISSUE TITLE
Is it possible to merge two multisample VCFs ?

### ISSUE THREAD

**Issue by rozaimirazali** [fritzsedlazeck/SURVIVOR#118]
Hi Fritz. I have 2 multisample VCFs, the first one is from 1000 Genome SV VCF (2,504 samples) and the other consists of my own samples (6,000 samples).

I want to merge these 2 files. Is it possible? When I try to do this, the output only shows the first sample from each of these 2 multisample VCFs.

Thanks

**Comment by fritzsedlazeck** [comment]
Sorry, not directly this way... You will see if the 6000 is generated by SURVIVOR that it carries over the information which sample had a variant by the support vector. but that is not ideal.
You want to see which of the 6000 has support by the 1000 genomes?

This way you should merge the 6000 individual VCF files + the 1000 genomes. 
If you are just interested in the portion of SV from 1000 genomes overlapping your call set than you can still do that with what you are doing.

Hope that helps
Fritz
