### ISSUE TITLE
Simulating NGS reads from SV introduced fasta file

### ISSUE THREAD

**Issue by MehmetGoktay** [fritzsedlazeck/SURVIVOR#12]
Hi Fritz,

I want to compare several SV callers which use short read data including (pindel, delly and lumpy) to see their accuracy. I have used SURVIVOR to introduce artifical SVs, but I couldnt find any parameter to simulate ngs reads from simulated  genome, I have only found long reads parameter.

Do I miss something or survivor only implemented to simulate long reads?

**Comment by fritzsedlazeck** [comment]
Hi,
It is only equipped for long reads. There are multiple short read simulator out there. Eg. Dwgsim, Mason.
Cheers
Fritz

**Comment by MehmetGoktay** [comment]
Thank you Fritz!
