### ISSUE TITLE
SURVIVOR merge 

### ISSUE THREAD

**Issue by Caro-Ca** [fritzsedlazeck/SURVIVOR#123]
Hi fritzsedlazeck,
I am trying to merge vcf files allocated in the same folder with only vcf files. 
The code used is:
`/home/silviav/SURVIVOR/Debug/SURVIVOR merge /hosts/linuxhome/chaperone/silviav/reads/YPS128/SRA/McClintock/sacCer2/SRR4074383.1_paired_R1/results/VCF 500 2 1 0 0 20 SV_all.vcf`
and the stdout message is: 
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```
The parameter represented for Disabled I didn't know what to introduce so I just basically assigned it to a 0. 

Hope you could help me find the problem. 
Thank you for your time.

**Comment by fritzsedlazeck** [comment]
Dear @Caro-Ca 
SURVIVOR requires a file that includes the paths and names to the vcf files. 
https://github.com/fritzsedlazeck/SURVIVOR/wiki#consensus-calling-or-comparing-svs-across-samples

Yeah the disabled was a relict but I didn't want to change the interface as I know people have integrated SURVIVOR in their pipelines. 

Cheers
Fritz
