### ISSUE TITLE
Issue generating pairwise comparison matrix

### ISSUE THREAD

**Issue by moldach** [fritzsedlazeck/SURVIVOR#124]
I've got a number of call sets for _C. elegans_. I've tried merging a combination of these call sets to a `sample_merged.vcf` and all work fine.

I thought there could be issues since I converted `breakdancer` output to `VCF` so here I've just used three files in the `sample_files` as a simple example of the issue with `SURVIVOR`: 

```
lumpy.vcf
pindel.vcf
tardis.vcf
```

As mentioned merging these appears to work:
```
[moldach@cedar5 VCF-FILES]$ ~/bin/SURVIVOR-master/Debug/SURVIVOR merge sample_files 1000 2 1 1 0 30 sample_merged.vcf
merging entries: 769
merging entries: 7840
merging entries: 749
```

However, there is no error (or output) when I try to create the comparison matrix:

```
[moldach@cedar5 VCF-FILES]$ ~/bin/SURVIVOR-master/Debug/SURVIVOR genComp sample_merged.vcf sample_merged.mat.txt
Merged Vcf file
Normalize output (1==yes, else no)
Output: pariwise overlap matrix
[moldach@cedar5 VCF-FILES]$ ll
total 45053
-rw-r----- 1 moldach moldach     3933 May  5 13:56 breakdancer.vcf
-rw-r----- 1 moldach moldach     4362 May  5 13:55 cnvnator.vcf
-rw-r----- 1 moldach moldach  3035446 May  5 14:02 deepVariant.vcf
-rw-r----- 1 moldach moldach   485312 May  5 13:56 delly.vcf
-rw-r----- 1 moldach moldach  2979757 May  5 13:57 gridss.vcf
-rw-r----- 1 moldach moldach      321 May  5 14:13 logFile
-rw-r----- 1 moldach moldach   139890 May  5 14:02 lumpy.vcf
-rw-r----- 1 moldach moldach   267917 May  5 14:03 manta.vcf
-rw-r----- 1 moldach moldach   119277 May  5 14:03 mindTheGap.vcf
-rw-r----- 1 moldach moldach  1558662 May  5 14:03 ngsep.vcf
-rw-r----- 1 moldach moldach 36976900 May  5 14:04 pindel.vcf
-rw-r----- 1 moldach moldach       32 May  5 14:21 sample_files
-rw-r----- 1 moldach moldach   978418 May  5 14:21 sample_merged.vcf
-rw-r----- 1 moldach moldach      663 May  5 14:15 survivor.sh
-rw-r----- 1 moldach moldach   520557 May  5 14:04 tardis.vcf
[moldach@cedar5 VCF-FILES]$
```

Your help is greatly appreciated.

**Comment by Caro-Ca** [comment]
Hi! 
I also have the same problem. 
I've got 4 vcf files that I merged by using `/home/silviav/SURVIVOR/Debug/SURVIVOR merge sample_files 1000 2 0 0 0 31 sample_merged.vcf` (This is just a small dataset that I used to understand SURVIVOR), and the merging was fine, but when I tried to create the comparison matrix I didn't get any output.

**Comment by fritzsedlazeck** [comment]
Hey @moldach @Caro-Ca  thanks for reaching out. 

the comparison matrix function now requires another parameter which indicates if the counts should be normalized or raw counts. 
So you need to be called like this:  
`~/bin/SURVIVOR-master/Debug/SURVIVOR genComp sample_merged.vcf 0 sample_merged.mat.txt`

That's what survivor is trying to tell you. 

Cheers
Fritz
