### ISSUE TITLE
Can SURVIVOR work with vcfs without header?

### ISSUE THREAD

**Issue by astulaaa** [fritzsedlazeck/SURVIVOR#126]
One of the CNV detection programs (CNVnator) output contained one line header in vcf
 and the file parser cannot open the file. My SV file has only duplications which are sorter by the position. Is there any way SURVIVOR can deal with that?
Example of my input from CNVnator:
TYPE    COORDINATE      SIZE    NormalizedRD    P-val1  P-val2  COL1    COL2    COL3                                                 
DUP     chr1:1635001-1752000    117000  1.41886 4.04724e-08     411000  1.62956e-07     478140  0.259348                             
DUP     chr1:83136001-83490000  354000  1.82362 0       939.166 0       1021.84 0.457598                                             
DUP     chr1:116583001-116660000        77000   1.4884  9.03539e-07     861917  2.98472e-06     1.06405e+06     0.223039             
DUP     chr1:161512001-161678000        166000  1.73613 0       11062.7 0       12855.6 0.440492                                     
DUP     chr1:192290001-192386000        96000   1.36988 1.40822e-06     6377.13 5.26661e-06     8363.82 0.00941176                   
DUP     chr1:234776001-234820000        44000   4.1361  0       2.31504 0       5.9965  0.491603                                     
DUP     chr2:108650001-108732000        82000   1.73223 0.00025393      8.51826e+06     0.000836588     9.81752e+06     0.389333     
DUP     chr2:111251001-111994000        743000  1.838   0       68.3844 0       71.693  0.443333                                     
DUP     chr2:116148001-116314000        166000  1.30335 1.19691e-05     19704.4 3.14383e-05     22739.1 0.0325521                    
DUP     chr2:231576001-231646000        70000   1.31706 0.0316835       111187  0.0699279       148631  0.0720721                    
DUP     chr3:75360001-75830000  470000  2.00096 0       43241.3 0       45333.5 0.379752                                             
DUP     chr3:129999001-130203000        204000  1.61608 0       2.31751e+07     0       2.42964e+07     0.34366                      
DUP     chr3:176010001-176088000        78000   1.3955  3.4452e-05      2.25294e+06     0.000100499     2.70627e+06     0.127688     
DUP     chr4:3889001-4189000    300000  1.54285 0       6560.45 0       7153.87 0.277279                                             
Thanks

**Comment by fritzsedlazeck** [comment]
I dont think that his an issue for SURVIVOR. It will include a header, but the VCF might not be 100% standard conform as important information about the genome and sample name might be missing. 
Thanks
Fritz
