### ISSUE TITLE
 SURVIVOR convertAssemblytics problem

### ISSUE THREAD

**Issue by MehmetGoktay** [fritzsedlazeck/SURVIVOR#128]
Hi Fritz,

I am interested in a tandem duplication event on one of the chromosome. We already know that one of the sample contains 4 extra copies. When I use assemblytics to call it. It identifies as tandem_expansion with 4 extra copies.

3	12363708	12379593	Assemblytics_b_1315	15883	+	Tandem_expansion	-15885	-2	ourAssembly_Contig_20:15168814-15168816:-	between_alignments
3	12363708	12379593	Assemblytics_b_1315	15883	+	Tandem_expansion	-15885	-2	ourAssembly_Contig_20:15168814-15168816:-	between_alignments
3	12363708	12379593	Assemblytics_b_1317	15883	+	Tandem_expansion	-15885	-2	ourAssembly_Contig_20:15168814-15168816:-	between_alignments
3	12363708	12379593	Assemblytics_b_1318	15883	+	Tandem_expansion	-15885	-2	ourAssembly_Contig_20:15168814-15168816:-	between_alignments

So far so good. Length is correct with 15885.

But when I use  SURVIVOR convertAssemblytics to creates this insertions with size 31768.

3	12363708	Assemblytics_b_1315	N	<INS>	.	LowQual	IMPRECISE;SVTYPE=INS;SVMETHOD=Assemblytics;CHR2=1;END=12379593;SVLEN=31768;PE=1	GT	1/1
3	12363708	Assemblytics_b_1316	N	<INS>	.	LowQual	IMPRECISE;SVTYPE=INS;SVMETHOD=Assemblytics;CHR2=1;END=12379593;SVLEN=31768;PE=1	GT	1/1
3	12363708	Assemblytics_b_1317	N	<INS>	.	LowQual	IMPRECISE;SVTYPE=INS;SVMETHOD=Assemblytics;CHR2=1;END=12379593;SVLEN=31768;PE=1	GT	1/1
3	12363708	Assemblytics_b_1318	N	<INS>	.	LowQual	IMPRECISE;SVTYPE=INS;SVMETHOD=Assemblytics;CHR2=1;END=12379593;SVLEN=31768;PE=1	GT	1/1

So it basically creates 4  Insertions with a doubled size. I would be fine if it was showing 4 insertions with the length of 15883 instead of 31768 (doubled). Or as a duplication event.

Could you please kindly tell me if there is a way to do this or is this just the way that survivor works.

Best,
Mehmet

**Comment by fritzsedlazeck** [comment]
Dear Mehmet,
thanks for pointing this out. I indeed found (I think) the cause of this problem. I have pushed the correction to github. Would you mind testing it out and see if that solves it?

Thanks
Fritz

**Comment by MehmetGoktay** [comment]
Hi Fritz,

I have tested it and it works now. 

Thanks,
Mehmet

**Comment by fritzsedlazeck** [comment]
thanks for letting me know.
Fritz
