### ISSUE TITLE
Running into this issue during make

### ISSUE THREAD

**Issue by skatragadda-nygc** [fritzsedlazeck/SURVIVOR#129]
`/SURVIVOR/Debug/../src/SURVIVOR.cpp:263: undefined reference to `density_VCF(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'`

**Comment by fritzsedlazeck** [comment]
Sorry forgot to update the make file. should be fixed now.
Thanks
Fritz

**Comment by skatragadda-nygc** [comment]
Thank you!
