### ISSUE TITLE
SURVIVOR merge not working

### ISSUE THREAD

**Issue by cccnrc** [fritzsedlazeck/SURVIVOR#134]
I have 2 simple VCF CNV file to explore SURVIVOR, generated through [GATK germline CNV](https://gatk.broadinstitute.org/hc/en-us/articles/360035531152--How-to-Call-common-and-rare-germline-copy-number-variants) , here the command I send

```
SURVIVOR merge \
            segments.vcf.list 1 -1 0 0 0 -1 segments.merged.vcf

```

Here `segments.vcf.list`:
```
cat segments.vcf.list 
/home/enrico/Dropbox/NY/twins_igan/GATK_CNV/PostGermlineCNVCaller_calls/A13665_PostGermlineCNVCaller/A13665.segments.vcf
/home/enrico/Dropbox/NY/twins_igan/GATK_CNV/PostGermlineCNVCaller_calls/A13661_PostGermlineCNVCaller/A13661.segments.vcf
```

And attached the 2 files (once compressed):
[A13661.segments.vcf.gz](https://github.com/fritzsedlazeck/SURVIVOR/files/5216336/A13661.segments.vcf.gz)
[A13665.segments.vcf.gz](https://github.com/fritzsedlazeck/SURVIVOR/files/5216340/A13665.segments.vcf.gz)

I get as output:
> merging entries: 4016
> merging entries: 3740

but the output file has only the header and no variant.

```
tail segments.merged.vcf
##FORMAT=<ID=LN,Number=1,Type=Integer,Description="predicted length">
##FORMAT=<ID=DR,Number=2,Type=Integer,Description="# supporting reference,variant reads in that order">
##FORMAT=<ID=ST,Number=1,Type=String,Description="Strand of SVs">
##FORMAT=<ID=QV,Number=1,Type=String,Description="Quality values: if not defined a . otherwise the reported value.">
##FORMAT=<ID=TY,Number=1,Type=String,Description="Types">
##FORMAT=<ID=ID,Number=1,Type=String,Description="Variant ID from input.">
##FORMAT=<ID=RAL,Number=1,Type=String,Description="Reference allele sequence reported from input.">
##FORMAT=<ID=AAL,Number=1,Type=String,Description="Alternative allele sequence reported from input.">
##FORMAT=<ID=CO,Number=1,Type=String,Description="Coordinates">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	A13665	A13661
```

Any idea why?

Thanks in advance for any help

**Comment by fritzsedlazeck** [comment]
I think that is something that I just fixed. The parser got confused if there is only an END tag in the info file.

Please download the code base and retry.
Thanks
Fritz

**Comment by cccnrc** [comment]
it works now! Thank you very much!
