### ISSUE TITLE
fail to simulate nested SVs like INV_del or INV_dup

### ISSUE THREAD

**Issue by Jingwen7** [fritzsedlazeck/SURVIVOR#138]
Hi @fritzsedlazeck,

Thanks for developing SURVIVOR!  I wanted to simulate nested SVs. I specify the number of INV_del and INV_dup I want to simulate in the parameter_file. But there is no INV_del and INV_dup in the resulting simulated.bed and simulated.vcf. Do you have an idea what could be causing this? Thank you!
my parameter_file looks like this: 
PARAMETER FILE: DO JUST MODIFY THE VALUES AND KEEP THE SPACES!
DUPLICATION_minimum_length: 100
DUPLICATION_maximum_length: 10000
DUPLICATION_number: 100
INDEL_minimum_length: 20
INDEL_maximum_length: 10000
INDEL_number: 100
TRANSLOCATION_minimum_length: 1000
TRANSLOCATION_maximum_length: 5000
TRANSLOCATION_number: 100
INVERSION_minimum_length: 600
INVERSION_maximum_length: 2000
INVERSION_number: 100
INV_del_minimum_length: 600
INV_del_maximum_length: 1000
INV_del_number: 50
INV_dup_minimum_length: 600
INV_dup_maximum_length: 1000
INV_dup_number: 50

Best,
Jingwen

**Comment by Jingwen7** [comment]
And the reference I'm using is chr20, chr21 and chr22.

**Comment by fritzsedlazeck** [comment]
@Jingwen7 thanks for posting this. Can you check (I would need to run it myself again since its been a while) if there are INV with adjacent DEL events? Back then I remember that I reported these events seperately. 
Thanks
Fritz

**Comment by Jingwen7** [comment]
@fritzsedlazeck Thanks for the quick reply! I checked the simulated.vcf. Just to comfirm, the first image shows a INVDUP, right? Because there is a INV and DUP share exact same coordinates. And the second image shows a INVDEL, since a INV and DEL are right beside each other. 
![image](https://user-images.githubusercontent.com/35582642/110400104-e80c4780-802b-11eb-8464-44ce0144651e.png)
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/35582642/110400958-8220bf80-802d-11eb-8be7-b037e82d101a.png">

**Comment by fritzsedlazeck** [comment]
yes right. that's how I implemented it . I wanted to use the existing types and not invent something new. 
Cheers
Fritz

**Comment by Jingwen7** [comment]
Thanks for the reply! I also want to ask a followup question about ngmlr and sniffles. After simulating SVs and simulating reads from the altered reference, I get alignment from several aligners (including ngmlr). And I used sniffles to call SVs from alignment. But the resulting vcf file from sniffles only contains less than 10 SVs (for each aligner), which is way below what I've simulated. Do you have any idea what is causing this? 

Best,
Jingwen

**Comment by fritzsedlazeck** [comment]
Maybe check in IGV to see if you can look at the SV and one other common thing would be the simulated coverage vs. the -s parameter from Sniffles that is set.

**Comment by Jingwen7** [comment]
Yes! The default -s parameter is 10, which is relatively large comparing to my simulated coverage (10x). It works now! Thank you very much! :)

**Comment by fritzsedlazeck** [comment]
great. 
I will close this issue. 
thanks
Fritz
