### ISSUE TITLE
sample names instead of file names (merge tool)

### ISSUE THREAD

**Issue by gnarzisi** [fritzsedlazeck/SURVIVOR#15]
Thank you for developing such a great tool !
We use SURVIVOR to merge Manta calls across multiple samples and we love how simple it is to run.

We have a small enhancement request. Would it be possible to include the actual sample names in the output multi-sample VCF ? 
Basically, we would like to have the sample name (extracted from the original VCF) to appear in the corresponding header column of the output multi-sample VCF. 
We typically build a list of absolute paths to the input VCF files and we would like just the sample name, instead of the long absolute path, to be listed in the output file after merging.

**Comment by fritzsedlazeck** [comment]
Yes that should be possible. I am currently traveling, but worst case I should have a fix next week.

**Comment by fritzsedlazeck** [comment]
Hey Giuseppe,
I have just uploaded the code for this. Please give it a try.
Thanks
Fritz

**Comment by gnarzisi** [comment]
New code tested and it worked like a charm. Thank you!

**Comment by fritzsedlazeck** [comment]
Np, let me know if you have other suggestions.
Thanks
Fritz
