### ISSUE TITLE
Plotting the comparison of multiple input VCF files after merging shows only coincidental cases

### ISSUE THREAD

**Issue by dKlee99** [fritzsedlazeck/SURVIVOR#151]
Hi, thanks for providing this amazing tool! 
I used survivor merge and genComp function to compare two vcfs but it only shows coincidental cases. The below is my code. 

In bash,
`SURIVOR merge sample_files 1000 2 1 1 0 30 sample_merged.vcf` 
`genComp sample_merged.vcf 0 sample_merged.mat.txt`
`perl -ne 'print "$1\n" if /SUPP_VEC=([^,;]+)/' sample_merged.vcf | sed -e 's/\(.\)/\1 /g' > sample_merged_overlapp.txt`

In R, 
`t=read.table("sample_merged_overlapp.txt",header=F)`
`library(VennDiagram)`
`venn.diagram(list(N15=which(t[,1]==1), T15=which(t[,2]==1)), fill = c("gray", "orange") , alpha = c(0.5, 0.5), cex = 2, lty =2, filename = "my_sample")`

And the result shows following,

![image](https://user-images.githubusercontent.com/82995207/133030162-8a43be0f-2fd0-4cae-8a9f-297cfd037814.png)

<img width="560" alt="1631639473793" src="https://user-images.githubusercontent.com/82995207/133303043-c442cd4a-a871-4109-b733-b4e604367b5b.png">

I'm new to programming and not sure how to solve this issue, your help is very much appreciated!

**Comment by Nazeeefa** [comment]
@DK In response to your question in #101; I wrote following to see overlap between three dataset i.e:

```
venn.diagram(list
             (File1=which(t[,1]==1), File2=which(t[,2]==1), File3=which(t[,3]==1)) , 
              fill = c("colour1", "colour2", "colour3") , 
             alpha = c(0.5, 0.5, 0.5), 
             cex = 2, lty =2, ext.text=TRUE, 
             filename = "output.jpeg")
```

**Comment by dKlee99** [comment]
> @dKlee99 In response to your question in #101; I wrote following to see overlap between three dataset i.e:
> 
> ```
> venn.diagram(list
>              (File1=which(t[,1]==1), File2=which(t[,2]==1), File3=which(t[,3]==1)) , 
>              fill = c("colour1", "colour2", "colour3") , 
>              alpha = c(0.5, 0.5, 0.5), 
>              cex = 2, lty =2, ext.text=TRUE, 
>              filename = "output.jpeg")
> ```

It worked! Thank you so much!!
