### ISSUE TITLE
Dropping INS during vcftobed

### ISSUE THREAD

**Issue by Phillip-a-richmond** [fritzsedlazeck/SURVIVOR#16]
Hey there Fritz,
In your newest release there is an issue with dropping of INS calls during the vcftobed conversion.  This is related to issue #14  where you were fixing the names of the variants being lifted from VCF to the bedpe step. 

Can we get an update where the INS are also represented within the bedpe output? Not sure exactly why there were lost.

Thanks,
Phil

**Comment by fritzsedlazeck** [comment]
Hey Phil,
sorry for that. I have updated the code, please give it a try. 
I really appreciate your reporting. 
Cheers
Fritz

**Comment by Phillip-a-richmond** [comment]
Fixed.
