### ISSUE TITLE
Error with merging VCF files for trio SVs

### ISSUE THREAD

**Issue by racemore** [fritzsedlazeck/SURVIVOR#168]
Hello Fritz,

I attempted to merge 3 family v4.2 VCF files and the output, viewed using bcftools, is pictured below. I also attempted to merge a two VCFs of the same individual's VCF file as a sanity check, hoping all the data would remain the same, but again, the output only shows the metadata like below. Any suggestions would be greatly appreciated as I am new to using this tool!

<img width="1440" alt="Screen Shot 2022-08-07 at 2 39 09 PM" src="https://user-images.githubusercontent.com/46336928/183306050-4d622480-214f-442e-8a8a-4178591cd122.png">

Thank you,
Aracely Moreno

**Comment by fritzsedlazeck** [comment]
Survivor doesn't work on compressed VCf files. My guess is that your input files were compressed.
Cheers
Fritz

**Comment by racemore** [comment]
That worked. Thanks!
