### ISSUE TITLE
error when running SURVIVOR merge

### ISSUE THREAD

**Issue by ytguojian** [fritzsedlazeck/SURVIVOR#17]
Hi, 
I want to merge my vcf files using 'SURVIVOR merge 925.gt.vcf 924.gt.vcf 1000 1 1 1 50 merge.vcf' 
But it has an error showing "VCF Parser: could not open file: ##fileformat=VCFv4.2"
How can I resolve this problem?
Cheers.

**Comment by fritzsedlazeck** [comment]
Hi,
you need to first create a file with the paths of the vcf files:
e.g.L *vcf > files
then you can run the merge;
SURVIVOR merge files 1000 1 1 1 50 merge.vcf

See here: (with the old interface)
https://github.com/fritzsedlazeck/SURVIVOR/wiki#consensus-calling-or-comparing-svs-across-samples
Thanks
Fritz
