### ISSUE TITLE
SURVIVOR  convertAssemblytics, issue for "Min size to keep"

### ISSUE THREAD

**Issue by Jhuang90** [fritzsedlazeck/SURVIVOR#171]
Hi Dr. Sedlazeck,

I like using SURVIVOR you developed, it is really convenient.
I just got a question about 'convertAssemblytics', I found when I converted my Assemblytics outcome (bed file) to a VCF file, I used 10 bp as a filter for "Min size to keep". However, when I checked the VCF outcome, it seems that all SV with exactly 10 bp size got removed from the vcf file, it that common to see? or is something wrong with "Min size to keep" setting? My SURVIVOR version is Version: 1.0.7.

Thanks,
Jun

**Comment by fritzsedlazeck** [comment]
Dear Jun, 
the min size is > not >= . I think that's what you are seeing here. 
Cheers
Fritz

**Comment by Jhuang90** [comment]
Hi Dr. Sedlazeck,

Thanks, it makes sense.

Best,
Jun
