### ISSUE TITLE
NUlls for sample names after merging VCFs

### ISSUE THREAD

**Issue by maxineliu** [fritzsedlazeck/SURVIVOR#175]
Hi, 
I used SURVIVOR to merge 12 single sample vcfs together.

The command I used is:
`SURVIVOR merge vcf_files 1000 1 1 1 0 30 merged.vcf`

The vcf_files is like:
```
cy201704
cy201804
cy201904
cy202304
cy202404
cy202504
cy206504
cy206604
cy206704
cy207104
cy207204
cy207304
```

How to fix this kind of problem? Thanks in advance!

Maxine

**Comment by fritzsedlazeck** [comment]
The vcf_files needs to hold the file names of the incividual vcf files and the paths if its run outside of the folder. 
Cheers
Fritz

**Comment by maxineliu** [comment]
Hi Friz,
Sorry for I don't make it clear. The vcf_files do include the correct paths (vcfs and vcf_files sitting in one folder) and the correct names (eg. cy201704 is the name of vcf file not just the sample name. I removed .vcf from cy201704.vcf because I tried this way to avoid null name ).

Maxine

**Comment by fritzsedlazeck** [comment]
so if you do a "ls cy201704" there is a file?
Can you post the error msg and maybe a few lines before ?

**Comment by fritzsedlazeck** [comment]
ah no worries :) happens
Fritz
