### ISSUE TITLE
Feature Request: testing against a control SV set

### ISSUE THREAD

**Issue by ebioman** [fritzsedlazeck/SURVIVOR#18]
I think one scenario which might often arise is that we have e.g.

 - SVs analyzed in a control group
 - SVs calls from a treated group (or group with a certain sickness)

Or alternatively that the assembly and the SV-caller would disagree with some assembly hypothesis and report SVs.

It would be great if an option would exist to define one set as background SVs which should be ignored, or flagged.
So essentially the opposite of "Consensus call from multipe SV calls (vcf files)" .

Cheers

**Comment by fritzsedlazeck** [comment]
Right now I am often using awk or grep to achieve this. 
1. Merge all the control + treated (Assuming in that order): SURVIVOR  merge files 1000 1 1 0 0 0 merged.vcf
2. awk ' $10 =="./.:0:0,0:--:NaN:NaN" {print $0}' merged.vcf > treated_only.vcf

I will think about building in such a filtering to make this easier. 
Thanks
Fritz

**Comment by ebioman** [comment]
Thx, indeed that is a very simple work-around
