### ISSUE TITLE
definition of some parameters when simulate SV

### ISSUE THREAD

**Issue by charliechen912ilovbash** [fritzsedlazeck/SURVIVOR#187]
Hi,

I have few questions about simulating SV that I couldn't find any answers in the tutorial:

1. what does `homozygous_ratio` means in `parameter_file` for `simSV`
2. what does `SNP mutations frequency` means in `simSV`
3. what does `scanreads` do and what is the meaning of `error profile file` in `simreads`
   For example, does any nanopore reads from normal human is appropriate as the input of `scanreads`?

Thank you very much

**Comment by fritzsedlazeck** [comment]
1. Rate of het vs hom Snv 
2. Frequency of random Snv mutations
3. Scan reads can measure error and size distribution that then can be used for simulating long reads 
Hope that helps
Fritz

**Comment by charliechen912ilovbash** [comment]
Thanks for the quick reply!
