### ISSUE TITLE
SURVIVOR scanreads does not work

### ISSUE THREAD

**Issue by wyzhangMPI** [fritzsedlazeck/SURVIVOR#19]
Hi,
   I am trying to use the latest version of SURVIVOR (v1.02) to simulate ONT reads based on "true" alignment data. The first step is to generate error file from the alignment data. Using the command line suggested, I cannot get the program running, however:
> samtools view ./MC_All_Albacore_trim_filtered_BWA.bam | ./SURVIVOR 2 scan 10000 error.txt
_Program: SURVIVOR (Tools for Structural Variations in the VCF format)
Version:

Usage: SURVIVOR <command> [options]

Commands:
-- Simulation/ Evaluation
        simSV   Simulates SVs and SNPs on a reference genome.
        scanreads       Obtain error profiles form mapped reads for simulation.
        simreads        Simulates long reads (Pacio or ONT).
        eval    Evaluates a VCF file after SV calling over simulated data.

-- Comparison/filtering
        merge   Compare or merge VCF files to generate a consensus or multi sample vcf files.
        filter  Filter a vcf file based on size and/or regions to ignore
        stats   Report multipe stats over a VCF file
        compMUMMer      Annotates a VCF file with the breakpoints found with MUMMer (Show-diff).

-- Conversion
        bincov  Bins coverage vector to a bed file to filter SVs in low MQ regions
        vcftobed        Converts a VCF file to a bed file
        bedtovcf        Converts a bed file to a VCF file
        smaptovcf       Converts the smap file to a VCF file (beta version)_

As you can see, with the command line above, I get the "help" information on the screen, and did not have anything to output.

Also tried:
>samtools view ./MC_All_Albacore_trim_filtered_BWA.bam | ./SURVIVOR scanreads 1000 1 error.txt

But still did not work.

Could you help to take a look at what is going on there?
Thanks!

**Comment by fritzsedlazeck** [comment]
I am sorry. I changed the interface and created a bug in that function. 
I just uploaded a fix for the code. 
Please give it another try and let me know.
Thanks
Fritz

**Comment by wyzhangMPI** [comment]
Yes, it works now.
Thanks!

Best,
Wenyu

------ Original Message ------
