### ISSUE TITLE
simreads in fastq format

### ISSUE THREAD

**Issue by charliechen912ilovbash** [fritzsedlazeck/SURVIVOR#192]
Hello, 
Is there any way to simulate reads in fastq format, instead of fasta format?

**Comment by sagarc88** [comment]
Hello, I have the same problem. simreads outputs file in fasta format but need it in fastq format for alignment. How was this problem solved?

**Comment by charliechen912ilovbash** [comment]
I used pbsim3 instead.
https://github.com/yukiteruono/pbsim3
