### ISSUE TITLE
SURVIVOR simreads

### ISSUE THREAD

**Issue by wyzhangMPI** [fritzsedlazeck/SURVIVOR#21]
Hi,
    Thanks for the solving the problem of scanreads funciton yesterday.
    However, I have the similar problem with simreads module:
> /home/wyzhang/opt/biosoftware/ONT_Analysis_Tools/SURVIVOR/Debug/SURVIVOR simreads ../../1.Deletion_Simulation/mm10_Chr1_Homo_DEL.fa ./ONT_error.txt 4 mm10_Chr1_Homo_DEL_ONT

I still got the help info on the screen:
No parameters provided:
1: Reference fasta file
2: error profile file (see scan)
3: Coverage
4: output prefix

I think I have given the program all the neccessary information, but it did not work again.

Best,
Wenyu

**Comment by fritzsedlazeck** [comment]
Hi Wenyu,
*facepalm*
so sorry for that. I have checked again all the modules and this should now been finally resolved. 
Cheers
Fritz
