### ISSUE TITLE
filtering normal SV from tumor SV

### ISSUE THREAD

**Issue by mdiaz09** [fritzsedlazeck/SURVIVOR#215]
When merging two VCFs is it possible to remove all lines that appear in both files using survivor, or should this be done using other tools, like bcftools?

**Comment by fritzsedlazeck** [comment]
There is a parameter for this in the merge command.
Also there is a supp= tag in the output VCF file if you want to use that on an already merged VCF 
Cheers
Fritz

**Comment by mdiaz09** [comment]
I am having trouble finding that option in the merge command, would you mind pointing it out?

**Comment by fritzsedlazeck** [comment]
Sorry sure. It's the 3rd argument. Set this to eg. 2 instead of 1 
So for example  survivor merge files 1000 2 1 0 0 0 output.

**Comment by mdiaz09** [comment]
Won't that generate an output with SVs present in both files? I am looking to remove all of the SV that overlap in the files, removing the SV from the normal file and leaving just the SVs from the tumor file.

**Comment by fritzsedlazeck** [comment]
Ooh sorry I misunderstood.. traveling. 
Yes than it's bcftools or you use the supp=1; tag.

**Comment by mdiaz09** [comment]
thanks!
