### ISSUE TITLE
Minimum number of supporting caller

### ISSUE THREAD

**Issue by wdecoster** [fritzsedlazeck/SURVIVOR#22]
Hi Fritz,

As a follow up on https://github.com/fritzsedlazeck/Sniffles/issues/61, I saw you suggested:

Step 3:
`SURVIVOR merge files 1000 1 1 0 0 0 output_merged.vcf`

Step 5:
`SURVIVOR merge 1000 0 1 0 0 0 output_genotyped_merged.vcf`

I assume in step 5 you missed the argument specifying the input vcfs and meant:
`SURVIVOR merge files_genotyped 1000 0 1 0 0 0 output_genotyped_merged.vcf`

But can you explain why in step 3 you recommend `1` for "Minimum number of supporting caller" and `0` in step 5? I'd expect both of them to be "1".

Cheers,
Wouter

**Comment by fritzsedlazeck** [comment]
Hi Wouter,
yes that is a bit tricky. 
I have seen some problems with ./. vs. 0/0 and how to handle these. Usually SURVIVOR ignores 0/0 and thus you wont see any output if all samples have 0/0... 
That is why. Frankly the pipeline is a bit experimental and as far as I know only ran by me and two other institutions. So feedback is very welcome. 

Thanks
Fritz

**Comment by wdecoster** [comment]
Alright, thanks for explaining. I'll let you know if I have any feedback.
