### ISSUE TITLE
somethings not understand

### ISSUE THREAD

**Issue by ytguojian** [fritzsedlazeck/SURVIVOR#24]
Hi,
I am using the merge option to merge my SV vcf files. However, there are two sections that I do not quite understand in using SURVIVOR merge"SURVIVOR merge sample_files 1000 2 1 1 0 30 sample_merged.vcf".
1.What does the 1000 means? You explained it as maximum allowed distance of 1kb. Does that mean the start position of the two SV sites could be 1kb distance? For example, one SV start position is chr1:100 and the other SV start position is chr1:1100 , and they can be merged as one sv site if they are the same SV type and on the same strand.
2. What does the 0 mean? You explained it as Estimate distance based on the size of SV.  What distance does it estimate?

Cheers

**Comment by fritzsedlazeck** [comment]
Hi,
soo each of the values correspond to one of the parameters listed when you execute the option with too few or no parameters.

`./SURVIVOR merge
Tab file with names
max distance between breakpoints
Minimum number of supporting caller
Take the type into account (1==yes, else no)
Take the strands of SVs into account (1==yes, else no)
Estimate distance based on the size of SV (1==yes, else no).
Minimum size of SVs to be taken into account.
Output prefix
`

So ad 1 (1000) is the maximum distance allowed for start and stop coordinates to be considered the same SVs. We ran multiple tests across different species and something between 500 and 1k seems to work the best. However, feel free to set your own parameter.

ad2: The 0 deactivates this option. I have implemented a beta version of this, but havent fully finished testing it. The estimation is based on the size and type of a SVs, but as I said I would not use it right now as it currently just points back to the default. This will be enabled once I did more testing on this option.

Let me know if you have other questions
Cheers
Fritz
