### ISSUE TITLE
some request on genotyping

### ISSUE THREAD

**Issue by ytguojian** [fritzsedlazeck/SURVIVOR#25]
Hi,
This tools is quite good in merging different call sets. I have merged 336 samples into one vcf file effectively. However, there is still one problem for me. In the merged vcf file, it only shows the 0/1, 1/1 ./. genotypes without 0/0. The problem is how to determine the ./. genotypes belong to. Are they belong to 0/0 or they are definitely ./. type ? Do you have some resolutions on this?

Cheers,

**Comment by fritzsedlazeck** [comment]
Thanks. 
Do you have 0/0 in your input files?
It should carry them over, but interpret them as not called. 

SURVIVOR inserts a ./. if the genotype is not defined (following the standard recommendation). 
It would be easier if you post a sample. 
Thanks
Fritz

**Comment by ytguojian** [comment]
Hi Fritz,
The problem is there is no 0/0 in the input files, so it shows ./. after SURVIVOR  merging. Because each input file has some different SV sites, so each different sites will show ./. for some samples. right？
How could I post a sample,  just copy and paste here?
Cheers,
Jian

**Comment by fritzsedlazeck** [comment]
can you add one of the input files?
Just e.g. gzip the file and drag it into the window. 
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
or send it per mail : fritz.sedlazeck@gmail.com

**Comment by fritzsedlazeck** [comment]
Oh and please also paste the command parameters that you used. 
Thanks
Fritz

**Comment by ytguojian** [comment]
[999.suvivor10.merge.vcf.new.gz](https://github.com/fritzsedlazeck/SURVIVOR/files/1849871/999.suvivor10.merge.vcf.new.gz)
[998.suvivor10.merge.vcf.new.gz](https://github.com/fritzsedlazeck/SURVIVOR/files/1849872/998.suvivor10.merge.vcf.new.gz)
[998.999.merge.vcf.gz](https://github.com/fritzsedlazeck/SURVIVOR/files/1849873/998.999.merge.vcf.gz)

**Comment by ytguojian** [comment]
Hi Fritz,
998.999.merge.vcf.gz is merge by SURVIVOR merge 998.999.name 1000 1 1 1 0 10 998.999.merge.vcf with files 999.suvivor10.merge.vcf.new.gz and 998.suvivor10.merge.vcf.new.gz
999.suvivor10.merge.vcf.new.gz and 998.suvivor10.merge.vcf.new.gz are files merge from 4 callers each with the similar method above.
Cheeers,

**Comment by fritzsedlazeck** [comment]
Thanks for sharing. I will take a look tomorrow.
Cheers
Fritz

**Comment by ytguojian** [comment]
Great! thanks a lot!
Cheers,
Jian

**Comment by ytguojian** [comment]
Some explanations :999.suvivor10.merge.vcf.new.gz is generated by merging 4 different SV caller results for sample999 using the similiar SURVIVOR command above. And also 998.suvivor10.merge.vcf.new.gz. 
My problem is that if some SV sites exist in 998.suvivor10.merge.vcf.new.gz as 0/1 but not in 999.suvivor10.merge.vcf.new.gz, then the merged file 998.999.merge.vcf.gz will show 0/1  ./. at these sites. right?
However, I want to determine the GT ./. as undetermined or the same as reference. Because I want to do GWAS  with the merged vcf  GT information. But I find that there are too many ./. in the file, so I want to further make sure those GTs.
Cheers,
Jian

**Comment by fritzsedlazeck** [comment]
Ah. No that is not supported by SURVIVOR. What you need to do is to generate the merged sample file (like you did) and then run a SV genotyper (e.g. SVtyper or SV2 etc. ) per sample. 
SURVIVOR does not assess the bam files for each sample, thus does not genotype the calls that are missing. 

Sorry
Fritz

**Comment by ytguojian** [comment]
OK, Thanks a lot!
