### ISSUE TITLE
Assemblytics output to vcf

### ISSUE THREAD

**Issue by JunKim-Worms** [fritzsedlazeck/SURVIVOR#26]
Hi,
Thank you so much for your effort to maintain this wonderful software.
I'd like to ask how to use ID for SURVIVOR option.

My goal is to convert Assemblytics output (bed) to a vcf file for SURVIVOR_ant, then use SURVIVOR_ant to annotate my structural variation. So, first I tried `./SURVIVOR bedtovcf assemblytics.output.bed DEL output.vcf` to convert bed to vcf, but it changed all variant types into deletion. I tried ALL, All, all, etc., but it showed
`Bed file`
`Type`
`Output vcf file`
repeatedly. I would be grateful if you added other explanations how to use it properly, which part should I change, or what `Type` I can use, etc.
Second, I tried to use `./SURVIVOR ID`, so I replaced ID to the number 11: Convert SV calls from Assemblytics: `./SURVIVOR 11` However, it didn't show any informative error message, but showed the same message with typing `./SURVIVOR`. Could you explain how to use `./SURVIVOR` properly?

Yours sincerely,
Thank you.
Jun.

**Comment by fritzsedlazeck** [comment]
Hi Jun,
thanks I have just added the Assemblytics parser to the new interface. The IDs are currently not lift over. I can work on that if you need that. 

Please clone the code and compile. 

Cheers
Fritz

**Comment by fritzsedlazeck** [comment]
Sorry I answered just one of you questions. I am behind on documentation, but I changed the interface recently to have less options and to have a similar interface like samtools and other methods. 
 
So if you type:
`
./SURVIVOR convertAssemblytics

`

now shows you the 3 parameter that are necessary.

**Comment by JunKim-Worms** [comment]
It worked really well. Thank you so much! I appreciate it.
