### ISSUE TITLE
SVTYPE <NA>

### ISSUE THREAD

**Issue by Madelinehazel** [fritzsedlazeck/SURVIVOR#28]
Hello, 

I've run SURVIVOR on the outputs of CNVnator, LUMPY, and Pindel, and I see that I have a significant number of SVs of type 'NA' in the output (~25%). 

For example:
1       43171   NA004SUR        N       <NA>    .       PASS    SUPP=1;SUPP_VEC=010;AVGLEN=295;SVTYPE=NA;SVMETHOD=SURVIVORv2;CHR2=1;END=43466;STRANDS=++        GT:LN:DR:ST:TY:CO       ./.:0:0,0:--:NaN:NaN    0/0:295:0,0:++:NA:1_43171-1_43466       ./.:0:0,0:--:NaN:NaN

and

1       563387  NA0014SUR       N       <NA>    .       PASS    SUPP=1;SUPP_VEC=010;AVGLEN=150;SVTYPE=NA;SVMETHOD=SURVIVORv2;CHR2=1;END=563537;STRANDS=++       GT:LN:DR:ST:TY:CO       ./.:0:0,0:--:NaN:NaN    0/0:150:0,0:++:NA:1_563387-1_563537     ./.:0:0,0:--:NaN:NaN

What are these? Are they records with conflicting SV types?

Thanks for your help!
Madeline

**Comment by fritzsedlazeck** [comment]
Hi,
thanks for reaching out. 
NA is reported when the SV type is not parsable (right now everything else than DEL, DUP, TRA, BND,INV, INS). I can extend this if you would check what type the variant was reported initially. From your example it was the second caller that you specified in the input.  

Thanks
Fritz

**Comment by Madelinehazel** [comment]
Hi Fritz, 
Thanks for responding so quickly! It looks like the <NA> types are coming from pindel's <RPL> type (replacement), which is an SV with inserted sequence around the breakpoint. Having the types extended to include RPL (basically an indel) might be helpful.

**Comment by fritzsedlazeck** [comment]
Thanks I will consider that. in the mean time if you want to include them you should run the merge without the type constrain. 
Thanks
Fritz
