### ISSUE TITLE
cend.first and cend.second in combine_svs.cpp

### ISSUE THREAD

**Issue by lsantuari** [fritzsedlazeck/SURVIVOR#29]
Hello Fritz,
Should not Line 141 and 142 be as follows?

cend.first = std::min(caller_info[i]->stops[j] - caller_info[index]->stops[0], **cend.first**);
cend.second = std::max(caller_info[i]->stops[j] - caller_info[index]->stops[0], **cend.second**);

https://github.com/fritzsedlazeck/SURVIVOR/blob/53437020f31809860a8af3285b6eea027f6ff805/src/merge_vcf/combine_svs.cpp#L141
https://github.com/fritzsedlazeck/SURVIVOR/blob/53437020f31809860a8af3285b6eea027f6ff805/src/merge_vcf/combine_svs.cpp#L142

Cheers,
Luca

**Comment by fritzsedlazeck** [comment]
Yes and thanks. I have pushed an update. 
Thanks
Fritz
