### ISSUE TITLE
misleading short program description

### ISSUE THREAD

**Issue by afif-elghraoui** [fritzsedlazeck/SURVIVOR#3]
At first, I skipped past this program because I thought it was just another SV detection tool for short reads. I heard from somewhere else that this tool does some format interchange and, going through the README now, became interested.

I strongly suggest that you change the repository description and the top of the README to better represent what this program can do.

**Comment by fritzsedlazeck** [comment]
Hey,
you are absolutely right. Sorry for that. I have changed the readme and started a wiki. Please check it out and let me know if this helps. I will continue extending the wiki. 
Cheers
Fritz

**Comment by afif-elghraoui** [comment]
Thanks! I think you've just overlooked updating the Github repository description. Other than that, everything looks great.

**Comment by afif-elghraoui** [comment]
Also, I'm a little bit confused about the difference between this repository and <https://github.com/fritzsedlazeck/SURVIVOR_ant>. The two seem pretty similar.

**Comment by fritzsedlazeck** [comment]
They are actually 2 projects. I have to wrap the SURVIVOR_ant up. Its meant to annotate SVs. You provide a vcf file of interest and it merges it with 0-n other vcf files (e.g. 1k genomes), 1-n bed files (e.g. repeats or other annotations) and 1-n gff files.

**Comment by afif-elghraoui** [comment]
The Github repository description still hasn't been corrected. That is actually the first thing one sees at the top of the page, before the README.

**Comment by fritzsedlazeck** [comment]
Ah I focused on the readme. Now I changed it. 
Thanks
Fritz
