### ISSUE TITLE
merge vcf SVTYPE 

### ISSUE THREAD

**Issue by tgong1** [fritzsedlazeck/SURVIVOR#31]
Hi,
I'm merging two VCF files from NanoSV using 
SURVIVOR merge input_files 1000 1 0 0 0 10 TUMOR_NORMAL_merged.vcf

I found the merged VCF files with SVTYPE:INV added, although the SVTYPE is BND in original VCF files. Please see the following example:

TUMOR.vcf 
chr1 | 179947 | 36 | T | T[chr1:181453[ | 45 | GAP;MapQual | SVTYPE=BND;SVMETHOD=NanoSV_v1.1.6;CIPOS=0,0;CIEND=0,0;SVLEN=1506;RT=0,1,0;GAP=997;MAPQ=60,60;PID=0.975,0.964;PLENGTH=0.536,0.412;RLENGTH=19764;DEPTHPVAL=0.558 | GT:DR:DV:GQ:HR:PL | 0/1:2,1:1,1:15:0,0:45,0,15

NORMAL.vcf
chr1 | 180588 | 1344 | C | C[chr1:181422[ | 60 | GAP;MapQual | SVTYPE=BND;SVMETHOD=NanoSV_v1.1.6;CIPOS=0,0;CIEND=0,0;SVLEN=834;RT=0,1,0;GAP=556;MAPQ=60,60;PID=0.941,0.932;PLENGTH=0.324,0.553;RLENGTH=4834;DEPTHPVAL=0.289 | GT:DR:DV:GQ:HR:PL | 1/1:0,0:1,1:6:0,0:60,6,0

TUMOR_NORMAL_merged.vcf
chr1 | 180588 | INV004SUR | N | <INV> | . | PASS | SUPP=2;SUPP_VEC=11;AVGLEN=1170;SVTYPE=INV;SVMETHOD=SURVIVORv2;CHR2=chr1;END=181422;CIPOS=-641,0;CIEND=-641,0;STRANDS=++ | GT:PSV:LN:DR:ST:TY:CO | 0/1:NA:1506:0,0:++:INV:chr1_179947-chr1_181453 | 1/1:NA:834:0,0:++:INV:chr1_180588-chr1_181422

ALL SVs with SVTYPE=BND in original VCF files are added as INV, except those with breakend in different chromosomes. How SURVIVOR infer the SVTYPE?
If I want to keep the SVTYPE in original VCF file, what should I do?

Thank you very much!

**Comment by fritzsedlazeck** [comment]
Hi,
yes that is expected. BND with both breakpoints on the same CHR are interpreted as INV while BND branching two chromosomes are treated as TRA/ BND .
It is a conversion that is unfortunately necessary to distinguish the types since as you probably know BND can encode any type. 

Sorry for the inconvenience.
Fritz

**Comment by fritzsedlazeck** [comment]
Oh one more thing. I took that notion from studying Manta and Lumpy. Just so you dont think I took that out of nowhere.
