### ISSUE TITLE
is there a way to simulate large deletions by simSV?

### ISSUE THREAD

**Issue by arkyl** [fritzsedlazeck/SURVIVOR#35]
Hi Fritz,
I tried to simulate the reads using simSV and notice that the par file has INDEL but no separate DEL or INS. I am wondering if there is a way to directly simulate large deletions, as many benchmark data are deletions. Thanks much!

Yue

**Comment by fritzsedlazeck** [comment]
Hi Yue,
there is currently no option to just simulate deletions. However, if you look at the output file you can easily just extract the simulated deletions.
I hope that helps. 
Fritz

**Comment by arkyl** [comment]
Sure Fritz. Thanks.
Yue
