### ISSUE TITLE
filter by min SV size using proportion of SV overlapping

### ISSUE THREAD

**Issue by alpreyes** [fritzsedlazeck/SURVIVOR#38]
Hello,

is it possible to filter out SV's from an input vcf file based on the proportion of overlap with regions in a bedpe file (similar to the -f option in bedtools intersect). I attempted to filter out SV's whose intervals had a 50% overlap with SV's in an exclusion bed file with the following command:

`SURVIVOR filter <input.vcf> <remove.bed> 0.5 -1 0.01 10 <out.vcf>`

However the out.vcf file did not have the expected output; there are SV's in out.vcf that do intersect with intervals with remove.bed that were not actually removed.

Does entering a decimal value for min SV size the way i did accomplish what I am intending to do?

**Comment by fritzsedlazeck** [comment]
Hi,
right now it is implemented that they just get removed if either of their SV breakpoints fall into the regions. I am using this to remove SV called over not reliable regions. 
SVs are mainly impacted over their two breakpoint locations where they are called. 

What do you intend to do with it? 
Cheers
Fritz

**Comment by alpreyes** [comment]
hi fritz,

Thanks for your quick response. 

basically out of all the SV's in my input.vcf file (here representing one iPSC clone derived from a patient) i want to remove all SV's that overlap with regions in my remove.bed file (here representing germline DNA derived from the same patient) by a certain proportion of their interval (including their breakpoints). 

The point is to identify variants seen in only these iPSC clones and NOT in the patient's germline. would the SURVIVOR filter be able to accomplish this?

Best,
Alberto

**Comment by fritzsedlazeck** [comment]
Do you have SV calls for both iPSC and germline? If so I would make a SURVIVOR merge and dig into the VCF with awk or grep to check the "SUPP_VEC=".

The filter does not work this way. You could try bedtools. I hope that works. 
Keep me posted
Fritz
