### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by jaesvi** [fritzsedlazeck/SURVIVOR#42]
I'm getting a compiling error when trying to install the latest release.
Below the relevant log lines:

> Building target: SURVIVOR
Invoking: Cross G++ Linker
g++  -o "SURVIVOR"  ./src/vcfs/Annotate_vcf.o ./src/vcfs/Combine_3_VCF.o ./src/vcfs/Compoverlap_VCF.o ./src/vcfs/Detect_nested.o ./src/vcfs/Filter_vcf.o ./src/vcfs/Generate_distMat.o ./src/vcfs/Merge_VCF.o  ./src/snp_overlap/Overlap_snps.o  ./src/simulator/Error_scanner.o ./src/simulator/Eval_vcf.o ./src/simulator/Pac_Simulator.o ./src/simulator/SV_Simulator.o ./src/simulator/Sim_reads.o ./src/simulator/test_cov.o  ./src/merge_vcf/IntervallTree.o ./src/merge_vcf/combine_svs.o  ./src/convert/ConvertMQ0Bed.o ./src/convert/Convert_Assemblytics.o ./src/convert/Convert_Bionano.o ./src/convert/Convert_Honey_tails.o ./src/convert/Convert_MUMmer.o ./src/convert/Convert_Pindel.o ./src/convert/Convert_VCF_to_BED.o ./src/convert/Convert_hapcut2.o ./src/convert/Process_Coverage.o ./src/convert/Process_Lumpy.o  ./src/analysis_sv/GIAB_summary.o ./src/analysis_sv/MT_identifier.o ./src/analysis_sv/MUMmer_overlap.o ./src/analysis_sv/Select_samples.o ./src/analysis_sv/Simplify_SVs.o ./src/analysis_sv/Summ_mat.o  ./src/CorrectAllele.o ./src/DetectDif.o ./src/Extract_Seq.o ./src/SURVIVOR.o ./src/Summarize_SV.o   
./src/convert/Convert_Assemblytics.o: In function `std::string::_M_data() const':
/home/cog/jvalleinclan/kloosterman/tools/SURVIVOR/Debug/../src/convert/Convert_Assemblytics.cpp:11: multiple definition of `print_header(std::string, _IO_FILE*&)'
./src/vcfs/Compoverlap_VCF.o:/home/cog/jvalleinclan/kloosterman/tools/SURVIVOR/Debug/../src/vcfs/Compoverlap_VCF.cpp:33: first defined here
./src/SURVIVOR.o: In function `official_interface(int, char**)':
/home/cog/jvalleinclan/kloosterman/tools/SURVIVOR/Debug/../src/SURVIVOR.cpp:248: undefined reference to `parental_phasing(std::string, std::string, std::string)'
collect2: error: ld returned 1 exit status
make: *** [SURVIVOR] Error 1

Is it on my side or is there a mis-definition somewhere?

**Comment by fritzsedlazeck** [comment]
Thanks for reaching out. This is just me trying to release a new version on an airport ^^ 
Please try again. I fixed it. 
Thanks
Fritz

**Comment by jaesvi** [comment]
Yeah, it works now. 
Thanks!
