### ISSUE TITLE
SVTYPE DUP merging into NA

### ISSUE THREAD

**Issue by MalhotraAnkit** [fritzsedlazeck/SURVIVOR#45]
Hi ,

I recently noticed that when merging two VCFs, all DUPs in my sample are merging into the NA type,

The command I ran is the following,

SURVIVOR merge vcf_files_raw_calls.txt 1000 1 1 -1 -1 -1 merged_SURVIVOR_1kbpdist_typesave.vcf

here's an example of the failed merge type

#merged line in SURVIVOR
chr1	10003	NA000SUR	N	<NA>	.	PASS	SUPP=2;SUPP_VEC=110;AVGLEN=135;SVTYPE=NA;SVMETHOD=SURVIVORv2;CHR2=chr1;END=10199;CIPOS=0,75;CIEND=-49,0;STRANDS=++	GT:PSV:LN:DR:ST:TY:CO	./.:NA:73:0,2:++:NA:chr1_10078-chr1_10150	./.:NA:197:0,3:++:NA:chr1_10003-chr1_10199	./.:NaN:0:0,0:--:NaN:NaN

#the two entries that got merged together into this are the following
chr1	10078	TJ10668	N	<DUP>	.	PASS	IMPRECISE;SVMETHOD=picky;END=10150;SVTYPE=DUP;RE=2;RNAMES=m151015_221903_42196_c100828522550000001823180911251523_s1_p0/91653/37610_37635,m150919_214537_42196_c100828492550000001823180911251585_s1_p0/30014/34259_34367;SVLEN=73;CIPOS=-47,47;CIEND=-76,76;NOTE=CIPOS_CIEND;ISVTYPE=TDSR(2)	GT	./.

chr1	10003	TJ36088	N	<DUP>	.	PASS	IMPRECISE;SVMETHOD=picky;END=10199;SVTYPE=DUP;RE=3;RNAMES=m150704_162046_42134_c100846082550000001823189212311577_s1_p0/140541/30105_30350,m150530_105730_00118_c100813682550000001823175310291582_s1_p0/88961/25088_25294,m150630_190056_00118_c100855592550000001823186312311594_s1_p0/131968/37141_37217;SVLEN=197;CIPOS=-2,69;CIEND=-1,90;NOTE=CIPOS_CIEND;ISVTYPE=TDSR(3)	GT	./.

Please advise,

**Comment by fritzsedlazeck** [comment]
Can you maybe send me a few entries of these VCF files? My email: fritz.sedlazeck@gmail.com
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
I am closing this since there was no interaction since a long time.
