### ISSUE TITLE
Duplication max length does not work

### ISSUE THREAD

**Issue by MehmetGoktay** [fritzsedlazeck/SURVIVOR#46]
Hi Fritz,

I used SURVIVOR simsv function with parameter file to introduce SVs in given genome.

For deletions and inversions I did not have any problem based on length. I introduced 1000 svs including indels duplications and inversions. Length of duplications are always greater than DUPLICATION_maximum_length. Could you please tell me how to solve this?

Best,
Mehmet

**Comment by MehmetGoktay** [comment]
Hi Fritz,

Did you have any time to check what would be the reason for this issue? 

Best,
Mehmet

**Comment by fritzsedlazeck** [comment]
Hi Mehmet,
dan you post the exact command you used and the parameter file? Otherwise please send it over to me: fritz.sedlazeck@gmail.com

Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Hi Mehmet,
sorry for the slow reply. I just fixed that bug and uploaded the code. 
Thanks for reaching out.
Fritz
