### ISSUE TITLE
merge vcf : Information for DR

### ISSUE THREAD

**Issue by StevenIg** [fritzsedlazeck/SURVIVOR#49]
Hello,

I use SURVIVOR merge to merge information from several software.
I wanted to know how DR information was calculated.
For exemple, with Manta this information is true, for Delly this information is false and for Lumpy we have only the information for the variant and not for the reference.

Thank you in Advance,
Regards,

Steven

**Comment by fritzsedlazeck** [comment]
Hi Steven,
This information is always tricky to parse since almost every tool is reporting it slightly different location or tag.
I tried to lift some over, but I frankly did not pay too much attention to it.
I can have a look
Cheers
Fritz

**Comment by fritzsedlazeck** [comment]
I have updated the code for Delly. 
Lumpy reports it a bit more tricky though. 
Cheers
Fritz
