### ISSUE TITLE
vcftobed info

### ISSUE THREAD

**Issue by yuntwang** [fritzsedlazeck/SURVIVOR#53]
Hi, recent I use the sub command vcftobed convert my vcf to bedpe and a little question:
my bedpe like this:
`chr11   5200306 5200306 chr11   5208306 5208306 DUP0090SUR      ,       -       +       DUP`
`chr11   5200309 5200309 chr11   5200348 5200348 INV0088SUR      ,       -       -       INV`
and I know the first 3 columns are the first breakpoint and the 4-6 columns are the stop breakpoint.
and the 7 column are SV type, and the 8-10 means?
the 9 means the first breakpoint dna strand info,10 means the stop breakpoint dna strand info?

**Comment by fritzsedlazeck** [comment]
Hi,
I tried to stick to the output that Lumpy provided. The , is just a space holder. - and + are indicating the directions parsed. That can be used for how to validate these SV later.
10 is actually the SV type. 7 is the ID from the vcf file that you used as the input. 

Does that help?
Thanks for reaching out.
Fritz

**Comment by yuntwang** [comment]
Thanks
