### ISSUE TITLE
Wrong merge outputs

### ISSUE THREAD

**Issue by songtaogui** [fritzsedlazeck/SURVIVOR#55]
Dear Fritz,

I have used `SURVIVOR merge` to merge 10 vcfs. However, there are several records that merged incorrectly.

The CMD I used:
`SURVIVOR merge test_list.txt 100 1 1 0 0 0 test.vcf`

And one of the incorrectly merged record `1 1123245 INS0051SUR` looks like this:

Vcfs | #CHROM | POS | ID | REF | ALT | QUAL | FILTER | INFO | FORMAT | Q100 | Q101 | Q102 | Q103 | Q104 | Q105 | Q106 | Q107 | Q108 | Q109
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
test.vcf: | 1 | 1123245 | INS0051SUR | N | <INS> | . | PASS | SUPP=4;SUPP_VEC=1000100101;AVGLEN=14.5;SVTYPE=INS;SVMETHOD=SURVIVORv2;CHR2=1;END=1123246;CIPOS=-50,0;CIEND=-50,0;STRANDS=+- | GT:PSV:LN:DR:ST:TY:CO | 1/1:NA:52:0,0:+-:DEL:1_1123195-1_1123246 | ./.:NaN:0:0,0:--:NaN:NaN | ./.:NaN:0:0,0:--:NaN:NaN | ./.:NaN:0:0,0:--:NaN:NaN | 1/1:NA:2:0,0:+-:INS:1_1123245-1_1123246 | ./.:NaN:0:0,0:--:NaN:NaN | ./.:NaN:0:0,0:--:NaN:NaN | 1/1:NA:2:0,0:+-:INS:1_1123245-1_1123246 | ./.:NaN:0:0,0:--:NaN:NaN | 1/1:NA:2:0,0:+-:INS:1_1123245-1_1123246

In the merged records, sample Q104, Q107 and Q109 has records. However, the raw vcf files of these samples don't have the `1	1123245` record:

 `grep -w "1123245" Q*.vcf` 

and I got:

Vcfs | #CHROM | POS | ID | REF | ALT | QUAL | FILTER | INFO | FORMAT | Sample
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Q104_grfmt.vcf: | 4 | 1123245 | Q104_gridss78_7902o | N | <INS> | 665.67 | PASS | END=1123246;SVTYPE=INS;SVLEN=2;CIPOS=0,0;CIEND=0,0 | GT:GQ:PSV | 1/1:665.67;Q104_gridss78_7902o
Q107_grfmt.vcf: | 4 | 1123245 | Q107_gridss78_8050o | N | <INS> | 757.62 | PASS | END=1123246;SVTYPE=INS;SVLEN=2;CIPOS=0,0;CIEND=0,0 | GT:GQ:PSV | 1/1:757.62;Q107_gridss78_8050o
Q109_grfmt.vcf: | 4 | 1123245 | Q109_gridss78_8683o | N | <INS> | 694.44 | PASS | END=1123246;SVTYPE=INS;SVLEN=2;CIPOS=0,0;CIEND=0,0 | GT:GQ:PSV | 1/1:694.44;Q109_gridss78_8683o

It seems that `SURVIVOR merge`  merged records on Chr4 to Chr1. 

Other incorrectly merged records in `test.vcf` are:

> INS0051SUR
> DEL0032515SUR
> INS0076470SUR
> DEL0077651SUR
> DUP00110047SUR

So, how  did this happen and how could I avoid this?
Since I failed to upload the vcf files to Github, I sent them to fritz.sedlazeck@gmail.com. Please check.

Thank you very much!

Best wishes,

Songtao Gui

**Comment by fritzsedlazeck** [comment]
Dear Songtao,
thanks for reaching out. I got your email and replied. I will let you know once I had the chance to take a look.
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Dear Sangtao,
I just uploaded a bug fix. Could you clone the code and check out if that works for you.
Thanks
Fritz

**Comment by songtaogui** [comment]
Dear Fritz,

Yes! It works.
Thank you for your kindly help.

Songtao Gui
