### ISSUE TITLE
Large SURVIVOR merge operation

### ISSUE THREAD

**Issue by lslochov** [fritzsedlazeck/SURVIVOR#56]
Hi Fritz, I'm planning on using SURVIVOR merge to combine the VCFs of individuals within a population group into a multi-sample VCF for the whole group. I'm currently considering whether to do the merge across all individuals (of which there are ~300), or to merge by population group (~30-40 individuals per group). Which would you recommend, and what command line parameters should I use for this merge?

Thanks in advance.

**Comment by fritzsedlazeck** [comment]
Hi,
We typically merge all the individuals at once using Survivor merge with a Max distance of 1000 and requiring typesavety.
I hope that helps.
Cheers
Fritz
