### ISSUE TITLE
character other than ACTG in simulated  reads

### ISSUE THREAD

**Issue by ramcn** [fritzsedlazeck/SURVIVOR#57]
Hello,

I am using survivor to generate simulated reads as below. But noticed some characters other than ACTG, like R, S, Y gets inserted in the generated reads which is giving me problem when running an alignment tool.

Is this expected? Below are the command and params I am using.
 
Commands:
SURVIVOR simSV my.parameter
SURVIVOR simSV hs37d5.fa my.parameter 0.01 0 my_sim_genome
SURVIVOR simreads my_sim_genome.fasta  NA12878_nano_error_profile_bwa.txt 10 my_reads

Params:
DUPLICATION_minimum_length: 100
DUPLICATION_maximum_length: 10000
DUPLICATION_number: 3
INDEL_minimum_length: 20
INDEL_maximum_length: 500
INDEL_number: 1
TRANSLOCATION_minimum_length: 1000
TRANSLOCATION_maximum_length: 3000
TRANSLOCATION_number: 2
INVERSION_minimum_length: 600
INVERSION_maximum_length: 800
INVERSION_number: 4
INV_del_minimum_length: 600
INV_del_maximum_length: 800
INV_del_number: 2
INV_dup_minimum_length: 600
INV_dup_maximum_length: 800
INV_dup_number: 2

**Comment by fritzsedlazeck** [comment]
Totally expected since the reference genome have these characters.
Thanks for reaching out .
Cheers
Fritz
