### ISSUE TITLE
merge produces invalid VCF when input VCFs contain a common sample name

### ISSUE THREAD

**Issue by Lenbok** [fritzsedlazeck/SURVIVOR#59]
This time my input VCF files used the same sample name (I would imagine this is a common situation), and the output VCF contained multiple sample columns with the same sample name. FYI this is not permitted according to the VCF specification.

**Comment by fritzsedlazeck** [comment]
This is the expected output. 
Survivor keeps the information of the merge.
What would you suggest as a generic solution?
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Hi just to update this. I have fixed this issue with the latest code version. 
Please clone and try again. Now if there are the same names the first occurrence has the original name but the subsequent occasions have a _1, _2, ... 
Thanks for reaching out.
Fritz
