### ISSUE TITLE
Same position in two different lines

### ISSUE THREAD

**Issue by Jordi-V** [fritzsedlazeck/SURVIVOR#61]
Hi Fritz,

congratulate for this tool! I want to merge the multiple vcfs ran by CNVnator. I used the SURVIVOR in order to do that. The result is strange, because in the final vcf I get in two different lines the same position. I ran the survivor as show you above:
SURVIVOR merge all_vcf_CNVnator 300 1 1 1 0 0 merge_vcf_CNVnator.vcf

I show you an example:

1       11551   DUP0038SUR      N       <DUP>   .       PASS    SUPP=23;SUPP_VEC=0000000000000000000000000100000000000000000000010000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100001000000000000010000000000000000010000100000000000000011000000000001000000000000000000000000000000000010000000000000010000000000000000001000001001000000000000000100000000000000000000000000000000000000000000010000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000;AVGLEN=9886.96;SVTYPE=DUP;SVMETHOD=SURVIVORv2;CHR2=1;END=21450;CIPOS=-150,0;CIEND=-150,0;STRANDS=-+   GT:PSV:LN:DR:ST:TY:CO   ./.:NaN:0:0,0:--:NaN:NaN        ./.:NaN:0:0,0:--:NaN:NaN to final

1       11551   DUP0039SUR      N       <DUP>   .       PASS    SUPP=20;SUPP_VEC=0000000000000000000000000000000000000000100000000001000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000010100000000010000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000100100000000010000000000000000000000000000000000010000000000000000000000100000000000000000000000000000000000000000001000000000000000000000000000000000000000010001000000000000000000000000000000000000010000000000000000000000000;AVGLEN=11392.5;SVTYPE=DUP;SVMETHOD=SURVIVORv2;CHR2=1;END=22950;CIPOS=0,0;CIEND=-150,150;STRANDS=-+    GT:PSV:LN:DR:ST:TY:CO   ./.:NaN:0:0,0:--:NaN:NaN        ./.:NaN:0:0,0:--:NaN:NaN... to final

So, why when I doing the merge of my 808 samples appear in the same position different lines? Because in this case there are the same SVTYPE and same STRAND....

Thanks for your time

Jordi

**Comment by fritzsedlazeck** [comment]
Hi Jordi,
Thanks for reaching out. The two are not merged since the distance of the end breakpoints are not within your required distance threshold (300).
I hope that explains it.
Cheers
Fritz
