### ISSUE TITLE
Limit size of variants

### ISSUE THREAD

**Issue by Jordi-V** [fritzsedlazeck/SURVIVOR#62]
Dear Fritz,

I have a new question about survivor. I found in the documentation that survivor dont work correctly for variants equal or les than 30bp, nowadays this is the same?? can we generate a consensus vcf with variants smaller than 30bp? I told that because in different issues the people in the last column put 0 and maybe is not correct...

Thanks for your time

Jordi

**Comment by fritzsedlazeck** [comment]
I don't recall that to be the case or mentioned in the documentation. Survior merge was not implement for Snps. 
Can you explain what you mean?
Fritz

**Comment by Jordi-V** [comment]
Hi Fritz,

In this page of Survivor: https://github.com/fritzsedlazeck/SURVIVOR/wiki

I found this sentence:

"In addition, we told SURVIVOR to only compare SV that are at least 30bp long and print the output in sample_merged.vcf."

In this text, I understand that Survivor only works for variants bigger or equal than 30 bp (called as SV). Can I use Survivor for indels with a size between 2-30bp or this merge is not implemented in the software? We are working with variant callers like Platypus( snps and indels smaller than 1000bp) and we wanted use this software to merge our vcf files. Is it possible??

Thanks! 
Jordi

**Comment by fritzsedlazeck** [comment]
This refers to the explanation of the command and the parameters:
`./SURVIVOR merge sample_files 1000 2 1 1 0 30 sample_merged.vcf`

which is the 30 in the second last parameter.
