### ISSUE TITLE
Merge strategy multiple samples and tools

### ISSUE THREAD

**Issue by maleasy** [fritzsedlazeck/SURVIVOR#65]
Hi,

I want to merge SVs for multiple samples, and multiple tools (delly, lumpy, manta). I have one VCF file per sample per tool.
What I would like to get is a merged VCF with the merged SVs, and one entry per sample.
I am unsure of how to go about it.
When I merge all files, I get each sample three times (presumably once for each tool).

E.g. if my `sample_list` file is 

      sample1.delly.vcf
      sample1.lumpy.vcf
      sample2.delly.vcf
      sample2.lumpy.vcf

SURVIVOR results in a VCF with 
  
     #CHROM	...	FORMAT	sample1	sample1	sample2	sample2

what I would like to get is

     #CHROM	...	FORMAT	sample1	sample2

How do I go about this?

Thanks,
Chris

**Comment by fritzsedlazeck** [comment]
Hi Chris,
usually we first do a merge for e.g. sample1 . here you can constrain if you want all the SV or just these that are supported by delly and lumpy.
Then you can merge the two resulting merged files. This should carry over some of the information about the individual delly and lumpy supports. 
I hope that helps
Fritz

**Comment by maleasy** [comment]
Hi Fritz,

thanks for your quick answer!
I will then merge hierarchically as you suggest, i.e. first merge the tools per sample, then all samples.

This will still give me one VCF genotype column per sample per tool.
There is no way to get a consensus genotype per sample, even if that would loose some information from the individual tools?

Thanks again,
Chris

**Comment by fritzsedlazeck** [comment]
Hi Chris,
what you can do and we are doing this often is a consensus set on the caller level (delly vs. lumpy). Then do a merge without the consensus to obtain a two sample VCF. 
There is no logic about the genotypes. I thought about this, but I dont know how to interpret 0/1 vs. 1/1.

The vcf will include the GT information from both callers.

Cheers
Fritz

**Comment by Thatguy027** [comment]
Hi there,

I would also like to merge by caller, then by sample. Following the advice on this post and other...

I merged by individual caller VCFs at the sample level:

VCF1
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	XZ2020_delly	XZ2020_manta	XZ2020_smoove
```

VCF2
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	XZ2019_delly	XZ2019_manta	XZ2019_smoove
```

Then merged the two above VCFs and obtained:

```
SURVIVOR merge sample_files 1000 0 0 0 1 30 merged.vcf
```
Where sample_files contains VCF1 and VCF2

VCF3
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	XZ2019_delly	XZ2020_delly
```

From what I understand about your post above, VCF3 should contain six "samples" 2 samples X 3 callers... Instead it looks like SURVIVOR just pulled the first caller from each individual sample VCF

I'm using SURVIVOR v1.03, but it looks like v1.0.6 is out and various merge issues were resolved, is this one of them? Or am I doing something wrong? 

Thanks!

**Comment by fritzsedlazeck** [comment]
Hi not quite.
So SURVIVOR performs a merge VCF1 and VCF2, but when you do the merge to VCF3 it looks as the VCF1 + VCF2 are just one sample each. 

If you want to have all 6 columns you need to do just one merge. 

What I am doing if the VCF1 + VCF2 requiring a min of 2 callers out of 3.  Then these VCF are representative for that sample. Thus VCF3 would be my multisample VCF file: 
`SURVIVOR merge sample_files 1000 1 1 0 0 30 merged.vcf`
Here I require the same SV type to merge the SVs. 

I hope that helps. Let me know
Fritz

**Comment by Thatguy027** [comment]
Ah, OK..I get it.

My problem with the 2/3 caller requirement to count as a representative call set for a sample is that Manta does a good job at calling insertions and delly and lumpy do not (at least in my experience). But I can just get around this by processing insertions separately and then requiring 2/3 as a representative variant set for other variants.

Thanks for the tip.

**Comment by fritzsedlazeck** [comment]
Yes you can process that separately. And I agree with your assessment :).

Cheers
Fritz
