### ISSUE TITLE
SURVIVOR merge files outputs no sites

### ISSUE THREAD

**Issue by sariya** [fritzsedlazeck/SURVIVOR#66]
Hi, 
I'm using Version: 1.0.6 for SURVIVOR to merge .vcf files.

```
~/path/SURVIVOR merge sample_files  1000 2 1 1 0 10 survivor_merged.vcf
merging entries: 8091

```
It says about merging entries but the .vcf file generated reports nothing but VCF headers, version. It stops after printing:

`#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT 550050_110003`
 
Is is because my VCFs contain same samples and survivor is unable to merge them?
Or, is it because samples in both VCFs are present in different order?
```

uname -a
Linux hgrcgridlogin 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
```

**Comment by fritzsedlazeck** [comment]
Hi,
this is just a guess:
SURVIVOR expects one to many file names in the sampe_files. It seems as there is just one file name listed. Usually it reports merging entries per vcf file parsed. 

Since you require the variants to be supported by at least 2 input files the output is only the header. 

Thanks for reaching out. 
Fritz

**Comment by sariya** [comment]
Sorry, I'm not following you. 
How do I get desired output? 
There are numerous sites present in both (i.e overlapping) VCF files, so some output would have been generated.

Thank you.

**Comment by fritzsedlazeck** [comment]
I think you should check your sample_files file. Does it list both files?

Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Did you had a chance to check this?
Was it resolved?
Thanks
Fritz

**Comment by sariya** [comment]
Ah, OK. There was a new line character missing in `sample_files` that caused the error. 
Thank you checking. :)

**Comment by sariya** [comment]
I think I'm having difficult time getting outupt. THe merged output contains only two samples. Both my input vcfs have 68 individuals.

**Comment by sariya** [comment]
I see. Is SURVIVOR appropriate when working with only two callers? 

When I provide 2 (`supported by 2 callers` ) and sample file with two VCFs, the merged file contains sites that aren't present in one VCF, or other.

**Comment by fritzsedlazeck** [comment]
Yes no problem. I just wanted to make the point that I am not distinguishing between different callers vs. different samples per file

Yes when you do that there should only be entries that are present in both VCF files. In your case that can mean that only one of the samples in each VCF file has the variant. 

The way your input is structured is unfortunately not what I had in mind when implementing survivor. Sorry for that.
