### ISSUE TITLE
Genotyping supported in SURVIVOR?

### ISSUE THREAD

**Issue by cedkid** [fritzsedlazeck/SURVIVOR#67]
Hello Fritz, 

I am merging three VCF files from mateclever, delly and pindel. I noticed that some of the SVs that were merged contained GT ./. (missing genotype). Does survivor merges SVs even if the GTs are missing?

Here below I have a merged SV from clever and pindel. The GT of this SV is missing in Clever, the GT of pindel here is 0/1. 

```

NC_000002.12    68706113        .       TATCCATCC       T       .       PASS    SUPP=2;SUPP_VEC=101;SVGLEN=-104;SVTYPE=DEL;SVMETHOD=SURVIVORv2;CHR2=NC_000002.12;END=68706121;CIPOS=0,675;CIEND=0,832;STRANDS=+-        GT:PSV:LN:DR:ST:QV:TY:ID:RAL:AAL:CO     ./.:NA:165:0,0:+-:.:DEL:.:TCTTCCTCATCTTTCTCTTTTAGTCCAACAGCAAGACCTATGACTCCTATTTCCAAAAATAGATCTGGAATCTGTCCCTCCGTTCCTATTGTGGCCACTGTGGTCCTCCTCCAGGATCTCTCCCCTGAGCTACTGCAGTAGCTTCCTCGGTGGACTTTTTATACTC:T:NC_000002.12_68706788-NC_000002.12_68706953  ./.:NaN:0:0,0:--:NaN:NaN        0/1:NA:42:0,0:+-:.:DEL:.:TATCCATCC:T:NC_000002.12_68706113-NC_000002.12_68706121


```
Kind regards,
Cedrick

**Comment by fritzsedlazeck** [comment]
Hi Cedrick,
yes SURVIVOR tries to parse the GT from the input file. If it is absent it puts a ./. at its place. 
I hope that makes sense. 
Cheers
Fritz

**Comment by fritzsedlazeck** [comment]
Hi Cedrick,
did that answer your question? I assumes so thus I am closing this issue. Let me know if not and we can reopen. 
thx
Fritz

**Comment by fgvieira** [comment]
I also noticed this behavior when merging several VCFs. If a SV is not present in a file, `SURVIVOR` sets it as `./.`.

But why not set it to `0/0`? If a given SV was not called, I guess we can assume it is homozygous reference (at least according to that caller), no?

**Comment by fritzsedlazeck** [comment]
Because we dont know if it is truly 0/0 -> reference allele only or not. This would need a re genotyping to make sure that there is no read that indicates the SV.  For SNV you wouldn't do that and that is why there is a gVCF and re genotyping methods. gVCF does not work for SVs.. :(
Hope that helps
Fritz

**Comment by fgvieira** [comment]
But if there was no SV on the original VCF, as far as the caller is concerned, the genotype is 0/0, no?
Why would it need to be re-genotyped?

**Comment by fritzsedlazeck** [comment]
Not necessarily. You see if you specify ./. you are uncertain. If you put a 0/0 you are certain. 

A caller (eg. Sniffles or Manta) can ignore SV if e.g. the read coverage is not sufficient or some mapping quality problems. Thus, an unknown genotype reflects this more than a homozygous reference. 

Therefore, I followed the recommendations from SNV calling.

**Comment by SunWinner01** [comment]
Seeing your conversation has given me a lot of inspiration.However, as a beginner, I’ve encountered some issues while trying to apply this knowledge, and I would greatly appreciate your assistance. Currently, I am using four SV callers for variant detection. My approach so far has been to merge the outputs from these four callers （manta delly gridss lumpy）for each sample using  SURVIVOR.

My question is: should I then merge the resulting VCF files from all samples? If so, what are the next recommended steps? Should I proceed with genotyping for the entire population?

Thank you very much for your time and any advice you can provide. I look forward to your response.

Best regards,
Weiying
@cedkid @fgvieira @fritzsedlazeck @lindenb @mschatz

**Comment by Wangping9** [comment]
> Seeing your conversation has given me a lot of inspiration.However, as a beginner, I’ve encountered some issues while trying to apply this knowledge, and I would greatly appreciate your assistance. Currently, I am using four SV callers for variant detection. My approach so far has been to merge the outputs from these four callers （manta delly gridss lumpy）for each sample using SURVIVOR.
> 
> My question is: should I then merge the resulting VCF files from all samples? If so, what are the next recommended steps? Should I proceed with genotyping for the entire population?
> 
> Thank you very much for your time and any advice you can provide. I look forward to your response.
> 
> Best regards, Weiying [@cedkid](https://github.com/cedkid) [@fgvieira](https://github.com/fgvieira) [@fritzsedlazeck](https://github.com/fritzsedlazeck) [@lindenb](https://github.com/lindenb) [@mschatz](https://github.com/mschatz)

Hello, have you solved this problem? I can't combine four SV callers at the moment because the sample missing rate after the combination is too high.
