### ISSUE TITLE
SURVIVOR filter using bed

### ISSUE THREAD

**Issue by Hughes-Shin** [fritzsedlazeck/SURVIVOR#68]
I tried to filter out some SV regions using bed file, but it seemed it didn't work. 
To check whether it works, I used bed files covering large part of hg38 chr1.

[chr1.bed]
(no header)
chr1   1   5000000

[vcf]
chr1    136934  pbsv.INS.17 G   GCAAGGGGCTCGGGCTGACCTCTCTCAGTGTGGGAGGGGCCGGTGTGAGGCAAGGGGCTCACGCTGACCTCTGTCCGCGTGGGAGGGCCGGTGTGAGACAAGGGGCTCGGGCTGACCTCTCTCAGCGTGGGAGGGGCTGGTGTGAGGCAAGGGGCTCGGGCTGACCTCTCTCAGCGTGGGAGGGGCCAGTGTGAGGCAAGGGCTCACACTGACCTCTCTCAGCATGGGAGGGGCCGGTGTGAGA    .   PASS    SVTYPE=INS;END=136935;SVLEN=243 GT:AD:DP:SAC    0/1:5,7:12:2,3,4,3 

[cmd line]
/Path/to/SURVIVOR filter my.vcf test chr1.bed -1 -1 0 -1 test_filt5.vcf

But it didn't filter any SVs, even though I changed some parameters.
Were there any points that I had missed? or was there any problem with my bed format?
(For information, I tried to filter vcf files generated by sniffles and pbsv2.1.1 and both have failed.)

Another question,
Among filtering before/after SURVIVOR merge vcfs, what would you recommend for population study?

**Comment by fritzsedlazeck** [comment]
the bed format is tab separated?

For larger studies I would filter before and then sort the file (just in case its not sorted). Subsequently do the merging step. 
Cheers
Fritz

**Comment by Hughes-Shin** [comment]
Ahhhh, you're right, my bad. I forgot to check tabs.
Now it works well.
Sorry for bothering you with minor things. 
Thanks.
