### ISSUE TITLE
Please consider adding descriptive comments and a short summary

### ISSUE THREAD

**Issue by sinamomken** [fritzsedlazeck/SURVIVOR#7]
Dear valuable authors,

Please consider adding comments describing function of each function, and possibly a short document describing the architecture and overall structure of the code.
This way, future researchers could more easily understand and improve your code.
Of course documentation has lower priority and you can postpone it. But please consider it in the last step.

Regards

**Comment by fritzsedlazeck** [comment]
Dear Sina,
yes I have been behind on documentation on this. I will try my best to improve things. 
Some key methods are described in the Wiki, I dont know if you saw that. 
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
I have updated the wiki and will work on putting more comments in the code.
https://github.com/fritzsedlazeck/SURVIVOR/wiki/Methods-and-Parameter

Thanks
Fritz

**Comment by sinamomken** [comment]
Dear Dr. Sedlazeck,
I read the wiki. Although it was technical (and as a novice was hard for me to deeply understand) but seemed detailed enough, at least for the end user.
Thank you for your efforts,
Sina

**Comment by fritzsedlazeck** [comment]
Hi Sina,
let me know with what you struggled. Its always hard to explain things when you are too used to running it. 
Thanks
Fritz

**Comment by sinamomken** [comment]
Dear Fritz,
You can also use Doxygen to create beautiful diagrams, useful for a new developer who wants to dive into your code (for purpose of updating your code or using some of its components).
Ryan Chikhi has used Doxygen before to create documents and diagrams of Minia.
With best wishes
