### ISSUE TITLE
SURVIVOR merge GT

### ISSUE THREAD

**Issue by apaul7** [fritzsedlazeck/SURVIVOR#70]
Hi Fritz,

Wanted to thank you for developing this tool. But I believe I have found a bug when trying to merge some calls from Manta. We are currently trying to merge the tumor only variants that are in the `tumorSV.vcf.gz` [results](https://github.com/Illumina/manta/tree/master/docs/userGuide#structural-variant-predictions). This vcf only has the `SR` and `PR`  in the genotype fields. And when running through SURVIVOR merge it pulls the first value as the `GT` field.

Input manta vcf:
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample _1
chr1    9061353 MantaBND:105:0:1:0:0:0:1        C       C]chr14:93246974]       .       PASS    SVTYPE=BND;MATEID=MantaBND:105:0:1:0:0:0:0;IMPRECISE;CIPOS=-292,293;BND_DEPTH=4;MATE_BND_DEPTH=2 PR      3,3
chr1    10194734        MantaDEL:108:0:1:0:0:0  A       <DEL>   .       PASS    END=10197381;SVTYPE=DEL;SVLEN=-2647;SVINSLEN=3;SVINSSEQ=GAA     PR:SR    1,6:1,5
```

Resulting merged vcf
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample_1
chr1    9061353 TRA000SUR       N       N[chr14:93246974[       .       PASS    SUPP=1;SUPP_VEC=1;AVGLEN=100000;SVTYPE=BND;SVMETHOD=SURVIVORv2;CHR2=chr14;END=93246974;CIPOS=0,0;CIEND=0,0;STRANDS=++    GT:PSV:LN:DR:ST:TY:CO   3,3:NA:84185621:0,0:++:TRA:chr1_9061353-chr14_93246974
chr1    10194734        DEL001SUR       N       <DEL>   .       PASS    SUPP=1;SUPP_VEC=1;AVGLEN=-3;SVTYPE=DEL;SVMETHOD=SURVIVORv2;CHR2=chr1;END=10197381;CIPOS=0,0;CIEND=0,0;STRANDS=+- GT:PSV:LN:DR:ST:TY:CO   1,6:NA:3:0,0:+-:DEL:chr1_10194734-chr1_10197381
```
Survivor command(v1.0.5):
```
SURVIVOR merge vcf.list 1000 1 1 1 0 1 merged.vcf
```
According to issue #67 SURVIVOR tries to locate the `GT` field and if it cannot find it SURVIVOR passes `./.` which is completely fine. The issue is currently the resulting vcf is not compatible with downstream tools. 
According to the vcf spec the `GT` field is not required but if it is present it has to be first, which could be why you pull the first value? Tried looking through the code to confirm but I have limited experience with C++ and figured it would be best to get your input.

Thanks!
-Alex

**Comment by fritzsedlazeck** [comment]
Hi Alex,
Yes you are right. It assumes that the first field in the per sample column is the gt. 
I can check for this and correct it early next week. If I am not back by Wednesday please ping me. It's kinda a crazy time...

Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Hi Alex,
thanks again for reaching out. I just pushed a correction that should avoid the problem. 
So if you could please clone the new code and let me know if this fixes the issue. 
Thanks
Fritz

**Comment by apaul7** [comment]
Hi Fritz,

That was very quick. Thank you! My quick glance over the resulting VCF now looks correct. I will go ahead and close the issue and let you know if I have any future problems. 
-Alex

**Comment by apaul7** [comment]
Hi Fritz,

Would you be able to add this bug fix into the latest release or make a new bug-fix release? We use docker images as the source of our software and try to create version controlled images and are a little hesitant to use the master branch as our source for SURVIVOR. If this would be an issue we could make a fork of master for us to use and then return to your tagged versions in future releases.

Thanks!
-Alex

**Comment by fritzsedlazeck** [comment]
Hi Alex,
usually not a problem. However, I just made one 5 days ago...
So please go ahead and fork it. 
sorry about this.
Fritz

**Comment by wangjiawen2013** [comment]
Dear,
what does "CIEND=0,0" mean ? In our textbook of  probability and statistics, there must be a confidence level corresponding to a confidence interval. so, how to explain "CIEND=0,0"？

**Comment by fritzsedlazeck** [comment]
Hi,
Cpos and cend are tags describing the variability of breakpoints. If you have merged 2 samples and the end points are the same it should be 0.
Now it depends sometimes a bit on the version, but I think I implemented it that way. I would need to check the source code. 
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Hi,
I just checked the code and it populates these tags correctly

Thanks
Fritz
