### ISSUE TITLE
error when installing SURVIVOR

### ISSUE THREAD

**Issue by LinXialab** [fritzsedlazeck/SURVIVOR#77]
Hi,

I got an error message as follow showed when I install SURVIVOR, could you please tell me how to deal with this one?

Looking forward your reply!
Best wishes!

Building file: ../src/vcfs/Annotate_vcf.cpp
Invoking: Cross G++ Compiler
g++ -O3 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/vcfs/Annotate_vcf.d" -MT"src/vcfs/Annotate_vcf.o" -o "src/vcfs/Annotate_vcf.o" "../src/vcfs/Annotate_vcf.cpp"
Finished building: ../src/vcfs/Annotate_vcf.cpp

Building file: ../src/vcfs/Combine_3_VCF.cpp
Invoking: Cross G++ Compiler
g++ -O3 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/vcfs/Combine_3_VCF.d" -MT"src/vcfs/Combine_3_VCF.o" -o "src/vcfs/Combine_3_VCF.o" "../src/vcfs/Combine_3_VCF.cpp"
Finished building: ../src/vcfs/Combine_3_VCF.cpp

Building file: ../src/vcfs/Compoverlap_VCF.cpp
Invoking: Cross G++ Compiler
g++ -O3 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/vcfs/Compoverlap_VCF.d" -MT"src/vcfs/Compoverlap_VCF.o" -o "src/vcfs/Compoverlap_VCF.o" "../src/vcfs/Compoverlap_VCF.cpp"
Finished building: ../src/vcfs/Compoverlap_VCF.cpp

Building file: ../src/vcfs/Detect_nested.cpp
Invoking: Cross G++ Compiler
g++ -O3 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/vcfs/Detect_nested.d" -MT"src/vcfs/Detect_nested.o" -o "src/vcfs/Detect_nested.o" "../src/vcfs/Detect_nested.cpp"
Finished building: ../src/vcfs/Detect_nested.cpp

Building file: ../src/vcfs/Filter_vcf.cpp
Invoking: Cross G++ Compiler
g++ -O3 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/vcfs/Filter_vcf.d" -MT"src/vcfs/Filter_vcf.o" -o "src/vcfs/Filter_vcf.o" "../src/vcfs/Filter_vcf.cpp"
../src/vcfs/Filter_vcf.cpp: In function ‘void translate(const char*, int, float, int, strentry&)’:
../src/vcfs/Filter_vcf.cpp:18:6: warning: variable ‘lumpy’ set but not used [-Wunused-but-set-variable]
  int lumpy = 0;
      ^
Finished building: ../src/vcfs/Filter_vcf.cpp

Building file: ../src/vcfs/Generate_distMat.cpp
Invoking: Cross G++ Compiler
g++ -O3 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/vcfs/Generate_distMat.d" -MT"src/vcfs/Generate_distMat.o" -o "src/vcfs/Generate_distMat.o" "../src/vcfs/Generate_distMat.cpp"
Finished building: ../src/vcfs/Generate_distMat.cpp

Building file: ../src/vcfs/Merge_VCF.cpp
Invoking: Cross G++ Compiler
g++ -O3 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/vcfs/Merge_VCF.d" -MT"src/vcfs/Merge_VCF.o" -o "src/vcfs/Merge_VCF.o" "../src/vcfs/Merge_VCF.cpp"
In file included from ../src/vcfs/Merge_VCF.cpp:7:0:
../src/vcfs/../GzipStream.h: In constructor ‘GzipStreamBuf::GzipStreamBuf(const char*)’:
../src/vcfs/../GzipStream.h:93:16: error: ‘BUFSIZ’ was not declared in this scope
    _init(fname,BUFSIZ);
                ^
../src/vcfs/../GzipStream.h: In member function ‘virtual int GzipStreamBuf::underflow()’:
../src/vcfs/../GzipStream.h:105:33: error: ‘EOF’ was not declared in this scope
    if(gzeof(this->gzin)) return EOF;
                                 ^
../src/vcfs/../GzipStream.h:109:12: error: ‘EOF’ was not declared in this scope
     return EOF;
            ^
../src/vcfs/Merge_VCF.cpp: In function ‘std::vector<strvcfentry> parse_vcf(std::string&, int)’:
../src/vcfs/Merge_VCF.cpp:560:91: error: ‘errno’ was not declared in this scope
   std::cerr << "VCF Parser: could not open file: " << filename.c_str() << " " << strerror(errno) << std::endl;
                                                                                           ^
make: *** [src/vcfs/Merge_VCF.o] Error 1

**Comment by fritzsedlazeck** [comment]
Can you clone the code again and try? We just had a similar report by another user that we could fix.
Thanks
Fritz

**Comment by LinXialab** [comment]
Thank you so much! It works!
