### ISSUE TITLE
SURVIVOR stalls when reference FASTA lacks newlines

### ISSUE THREAD

**Issue by lcoombe** [fritzsedlazeck/SURVIVOR#8]
Hello,
I've been trying to run LRSIM to generate some simulated human reads, and I've noticed that the run is stalling at the initial SURVIVOR stage. (Ie. stuck there for > 12 hours).
After doing some tests, I suspect that it is due to my reference FASTA file lacking newlines for a given sequence. 

Ex. for e. coli tests:
`SURVIVOR 0 ./ecoli.fa ./test1.hap.parameter 0 ./test1.hap 1000`
completes in under a second (fasta has 80 residues per line)

while
`SURVIVOR 0 ./ecoli_noNewlines.fa ./test1.hap.parameter 0 ./test1.hap 1000`
stalls, and I aborted it after ~4 minutes (fasta has all residues for a sequence on one line).

I'm just wondering if that is a known formatting requirement for running SURVIVOR?

Thanks!
Lauren

**Comment by fritzsedlazeck** [comment]
Hi Lauren,
thanks for pointing this out. Yes the way I read in files assumes a maximum number of characters per line (200,000 to be precise). I will add that to the requirements. 
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
I just updated the Readme. I hope that is sufficient. 
Thanks
Fritz

**Comment by lcoombe** [comment]
Thank you!

**Comment by sjackman** [comment]
It'd be great if SURVIVOR could either handle long lines (one line per sequence) or output an error message and exit if it detects long lines. The current behaviour of hanging indefinitely is mysterious and difficult to troubleshoot.

**Comment by fritzsedlazeck** [comment]
sorry for that. 
I assume you were using the option 1 ?

**Comment by fritzsedlazeck** [comment]
Hi Shaun,
I agree that is an annoying thing. I tend to use getline(char*, size) in C to read in the file line by line. The function I am using is requiring a char and an indication of the maximum size to read in per line. 
If the line is exceeding this size the whole thing hangs....

I have searched around and found a way around that using getline(string) from ifstream. I have just updated and pushed the section from option 1. Please give it a try and let me know if that works for you.

sorry for the inconvenience. 
Fritz

**Comment by sjackman** [comment]
Thanks for your quick response, Fritz!

I'm using [LRSIM](https://github.com/aquaskyline/LRSIM) to simulate linked reads, and it's running SURVIVOR for me. The command line is…
```
SURVIVOR 0 GRCh38.fa sim.lr.hap.parameter 0 sim.lr.hap 0
```

For future reference, the the commit that hopefully resolves this issue is 2f5f94e00959fb448215c3e5f925d289cbd980d8

**Comment by fritzsedlazeck** [comment]
Let me know if you ran in any other problem.
