### ISSUE TITLE
SURVIVOR merge and size-based distance estimation

### ISSUE THREAD

**Issue by ggstatgen** [fritzsedlazeck/SURVIVOR#80]
Hi

Thanks for developing SURVIVOR. I'm testing the `merge` function to try and find SVs shared by two vcf sets. Of course the definition of 'intersection' will vary depending on what we consider a SV overlap. I understand you provide two parameters to deal with this in `SURVIVOR merge`:

1. max distance between breakpoints: if I understand correctly, if you set this to 500 it means that overlap=TRUE if variant_set1_start = variant_set2_start +/- [1,500] AND variant_set1_end = variant_set2_end +/- [1,500]. Is this correct?

2. Estimate distance based on the size of SV. This sounds really interesting and I guess it makes sense biologically. A 90% overlap on a pair of small SVs is more interesting and potentially more likely to indicate a real biological signal overlap than a 90% overlap between two huge SVs.

My questions is - how does 2. work currently. I have tried to run an intersection between to set with 2. set to `1` and then `0`, but I see no difference between the two output files.

My command is as follows:
```
survivor_input 500 2 1 0 0 50 output.vcf
survivor_input 500 2 1 0 1 50 output.vcf
```
Any thoughts greatly appreciated. Thanks!

**Comment by fritzsedlazeck** [comment]
Yes. Sorry to say the second was a beta version some time ago. I deactivated it but didn't want to change the interface to confuse others or needed to change scripts.
Sorry about the confusion.
Fritz

**Comment by ggstatgen** [comment]
Thanks Fritz - no problem. Do you plan on re-implementing this at some point?

**Comment by fritzsedlazeck** [comment]
Yes thinking about it. It's basically implemented in Sniffles... 
Thanks
Fritz

**Comment by ggstatgen** [comment]
Thanks a final related question if I may. I'm trying to parametrise a run of `SURVIVOR merge` by the max distance between breakpoints parameters. I see something like this
```
   MAXDIST SV_IN_COMMON
     <dbl>        <dbl>
 1       1           10
 2       2         1919
 3       3         3643
 4       5         3808
 5      10         4048
 6      20         4468
 7      30         4711
 8      50         5447
 9     100         8188
10     200         9978
11     300        10540
12     500        11366
13     600        11429
14     900        11605
15    1000        11643
16    2000        11724
17    5000        11674
18    7000        11550
19   10000        11356
```
As you can see, past 2000bp the intersection count goes down slightly. What does this mean? Do you perhaps not count when SV1 from set1 intersects with 2 or more SVs from set2? Apologies if this is something very obvious/stupid to ask.

**Comment by fritzsedlazeck** [comment]
I do allow a merge of svs insight of the sample without reporting/ counting it. You can see the in the gt field. 
I don't fully understand the table, but that is what I would guess..
Thanks
Fritz
