### ISSUE TITLE
Can SURVIVOR Merge PBSV results？

### ISSUE THREAD

**Issue by biomichal** [fritzsedlazeck/SURVIVOR#82]
Hi Fritz,

I wonder whether SURVIVOR can merge pbsv (version 2) results? Or is it necessary to adjust the format of Pbsv 2 results to feed SURVIVOR.

Thanks

**Comment by fritzsedlazeck** [comment]
Hi,
If pbsv is producing a vcf file it should work or is there something special you have in mind?
Thanks
Fritz

**Comment by biomichal** [comment]
Yes, below is the VCF format of of PBSV results. I am not sure whether SURVIVOR can work normally bescause there is a little difference form the results of SNIFFLES and others.
 
> ##fileformat=VCFv4.2
##fileDate=2019-04-14T14:25:55.665Z
##source=pbsv 2.2.0 (commit v2.2.0)
##PG="pbsv call -j 5 -m 30 --min-cnv-length 1K --max-ins-length 10K --max-dup-length 100K test.fa test.svsig.gz test.vcf"
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the structural variant described in this record">
##INFO=<ID=SVLEN,Number=.,Type=Integer,Description="Difference in length between REF and ALT alleles">
##INFO=<ID=SVANN,Number=.,Type=String,Description="Repeat annotation of structural variant">
##INFO=<ID=CIPOS,Number=2,Type=Integer,Description="Confidence interval around POS for imprecise variants">
##INFO=<ID=MATEID,Number=.,Type=String,Description="ID of mate breakends">
##INFO=<ID=MATEDIST,Number=1,Type=Integer,Description="Distance to the mate breakend for mates on the same contig">
##INFO=<ID=IMPRECISE,Number=0,Type=Flag,Description="Imprecise structural variation">
##INFO=<ID=SHADOWED,Number=0,Type=Flag,Description="CNV overlaps with or is encapsulated by deletion">
##ALT=<ID=INV,Description="Inversion">
##ALT=<ID=DUP,Description="Duplication">
##ALT=<ID=CNV,Description="Copy number variable region">
##FILTER=<ID=Decoy,Description="Variant involves a decoy sequence">
##FILTER=<ID=NearReferenceGap,Description="Variant is near (< 1000 bp) from a gap (run of >= 50 Ns) in the reference assembly">
##FILTER=<ID=NearContigEnd,Description="Variant is near (< 1000 bp) from the end of a contig">
##FILTER=<ID=InsufficientStrandEvidence,Description="Variant has insufficient number of reads per strand (< 1).">
##FILTER=<ID=NotFullySpanned,Description="Duplication variant does not have any fully spanning reads.">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Read depth per allele">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read depth at this position for this sample">
##FORMAT=<ID=SAC,Number=.,Type=Integer,Description="Number of reads on the forward and reverse strand supporting each allele including reference">
##FORMAT=<ID=CN,Number=1,Type=Integer,Description="Copy number genotype for imprecise events">
##reference=file://test.fa
##contig=<ID=chr1,length=xxxxxx>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	test
chr1	18177	pbsv.DEL.0	<Sequence>	T	.	PASS	SVTYPE=DEL;END=18520;SVLEN=-343	GT:AD:DP:SAC	0/1:6,10:16:2,4,5,5
chr1	22700	pbsv.BND.chr1:22700-chr1:146853212	G	G]chr1:146853212]	.	PASS	SVTYPE=BND;CIPOS=-6,5;MATEID=pbsv.BND.chr1:146853212-chr1:22700;MATEDIST=146830512	GT:AD:DP	1/1:0,5:5
chr1	27767	pbsv.INS.73	T	<Sequence>	.	PASS	SVTYPE=INS;END=27767;SVLEN=43	GT:AD:DP:SAC	0/1:16,42:58:10,6,21,21
chr1	184242	pbsv.CNV.304053	C	<CNV>	.	PASS	SVTYPE=cnv;END=187337;SVLEN=3095	CN	8
chr1	215917	pbsv.SPLIT.DUP.98	T	<DUP>	.	PASS	SVTYPE=DUP;END=215935;SVLEN=18	GT:AD:DP:SAC	0/1:27,10:37:6,21,6,4

**Comment by fritzsedlazeck** [comment]
From a quick look this should be fine. Pacbio recently used survivor two for our ccs read manuscript.
Thanks
Fritz

**Comment by chadsmith123** [comment]
SURVIVOR does not appear to be parsing the read depth for pbsv. VCFs are attached. 

$ SURVIVOR --version
Program: SURVIVOR (Tools for Structural Variations in the VCF format)
Version: 1.0.7

$ SURVIVOR merge onerec_files.txt  0 1 0 0 0 0 one_rec_survivor.vcf

The original PBSV vcf:
pbsv.INS.4	GT:AD:DP:SAC	0/1:7,8:15:5,2,5,3

SURVIVOR:
GT:PSV:LN:DR:ST:QV:TY:ID:RAL:AAL:CO	0/1:NA:6824:0,0:+-:.:INS:pbsv.INS.4:C:CAAAAG...

[one_rec_survivor.vcf.txt](https://github.com/fritzsedlazeck/SURVIVOR/files/4372317/one_rec_survivor.vcf.txt)
[onerec_files.txt](https://github.com/fritzsedlazeck/SURVIVOR/files/4372318/onerec_files.txt)
[pbsv_onerec.vcf.txt](https://github.com/fritzsedlazeck/SURVIVOR/files/4372319/pbsv_onerec.vcf.txt)
[snif_onerec.vcf.txt](https://github.com/fritzsedlazeck/SURVIVOR/files/4372320/snif_onerec.vcf.txt)

**Comment by fritzsedlazeck** [comment]
Thanks. Yes that can be. I did so far not extend the genotype field parser much.. I will put that in for the next release.
Thanks
Fritz

**Comment by chadsmith123** [comment]
Thanks, do you have a release date pending?

**Comment by chadsmith123** [comment]
Or can I modify the pbsv vcfs prior to SURVIVOR as a quick fix to get the read depth?

**Comment by fritzsedlazeck** [comment]
Sorry currently slammed with all the craziness. 
I can open up the parser and push to the github.
 However, pbsv is a bit strange:
`GT:AD:DP:SAC    0/1:7,8:15:5,2,5,3`
I dont know what to parse here. It does not say 7 is the reference, 8 is the alternative 
It also does not say that for SAC. And it does not have that information in the INFO field. 

Programs often report DR:DV in the genotype filed to indicate the # reads supporting the reference (DR) or the variant (DV). SURVIVOR is currently quite specialized for a few callers to parse that information but I can open that up. 

Thanks
Fritz

**Comment by chadsmith123** [comment]
Here is a [github issue](https://github.com/PacificBiosciences/pbbioconda/issues/267
) asking about AD. PBSV says:
"We follow VCF standard: https://gatkforums.broadinstitute.org/gatk/discussion/1268/what-is-a-vcf-and-how-should-i-interpret-it"

This doc says AD = [ref, alt]:

1   899282  rs28548431  C   T   [CLIPPED] GT:AD:DP:GQ:PL    0/1:1,3:4:26:103,0,26

At this site, ... there were only a total of 4 reads at this site (DP =4), 1 of which was REF (=had the reference base) and 3 of which were ALT (=had the alternate base) (indicated by AD=1,3).

**Comment by fritzsedlazeck** [comment]
oh great... there are so many standards for VCF.... between us you can define whatever you want... 

I have just pushed code according to this. Please test it out and let me know if that works.
Cheers
Fritz

**Comment by chadsmith123** [comment]
Unfortunately this did not work. Please let me know how I can help.
```

(base) MLI-JGM197:survivor smithch$ which ${SURVIVOR}
/Users/smithch/git/SURVIVOR/Debug/SURVIVOR
(base) MLI-JGM197:survivor smithch$ ${SURVIVOR} merge onerec_files.txt 0 1 0 0 0 0 one_rec_survivor.vcf
merging entries: 1
merging entries: 1
(base) MLI-JGM197:survivor smithch$ bcftools view one_rec_survivor.vcf -H |head -n1 |cut -f3,9,10,11
pbsv.INS.4	GT:PSV:LN:DR:ST:QV:TY:ID:RAL:AAL:CO	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	0/1:NA:6824:0,0:+-:.:INS:pbsv.INS.4:C:CA...
```
