### ISSUE TITLE
pos is 0 in merged vcf

### ISSUE THREAD

**Issue by suyanan** [fritzsedlazeck/SURVIVOR#83]
when merged two vcfs from sniffles ouput, one SV is

11	196368	TRA00579551SUR	N	<TRA>	.	PASS	SUPP=2;SUPP_VEC=11;AVGLEN=100000;SVTYPE=TRA;SVMETHOD=SURVIVORv2;CHR2=17;END=0;CIPOS=0,452;CIEND=0,0;STRANDS=+-	GT:PSV:LN:DR:ST:TY:CO	1/1:NA:684073161:0,3:+-:TRA:11_196820-17_7	1/1:NA:684073606:0,1:+-:TRA:11_196368-17_0

END=0

vcf is 1 base, bed is 0 base.

**Comment by fritzsedlazeck** [comment]
Thanks for pointing this out. Sniffles sometimes report the 0 based. 
SURVIVOR just takes this position and does not alter them. 
Thanks
Fritz
