### ISSUE TITLE
Merge SVLEN issue

### ISSUE THREAD

**Issue by WEClarke** [fritzsedlazeck/SURVIVOR#84]
Hi Fritz,

I noticed an issue where the SVLEN is incorrect in some Manta merge results. Looks to me like the SVLEN is being set off of the SVINSLEN reported by Manta (even though this is a DEL). Here are the original records.
```
chr1    108190708       MantaDEL:7308:0:1:0:1:0 A       <DEL>   532     PASS    END=108194629;SVTYPE=DEL;SVLEN=-3921;SVINSLEN=1;SVINSSEQ=T      GT:FT:GQ:PL:PR:SR       0/1:PASS:380:582,0,377:23,9:12,13
chr1    108190708       MantaDEL:6126:0:1:0:0:0 A       <DEL>   546     PASS    END=108194629;SVTYPE=DEL;SVLEN=-3921;SVINSLEN=1;SVINSSEQ=T      GT:FT:GQ:PL:PR:SR       0/1:PASS:303:596,0,300:18,13:11,11
```
<br>
Here is the merged result

```
chr1    108190708       MantaDEL:6126:0:1:0:0:0 A       <DEL>   546     PASS    SUPP=2;SUPP_VEC=11;SVLEN=-1;SVTYPE=DEL;SVMETHOD=SURVIVOR1.0.6;CHR2=chr1;END=108194629;CIPOS=0,0;CIEND=0,0;STRANDS=+-    GT:PSV:LN:DR:ST:QV:TY:ID:RAL:AAL:CO     0/1:NA:1:35,22:+-:532:DEL:MantaDEL:7308:0:1:0:1:0:NA:NA:chr1_108190708-chr1_108194629   0/1:NA:1:29,24:+-:546:DEL:MantaDEL:6126:0:1:0:0:0:NA:NA:chr1_108190708-chr1_108194629
```
<br>
Cheers,
Wayne

**Comment by fritzsedlazeck** [comment]
You are right. I will check and correct that. 
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
I just pushed a change for the parser to distinguish between INSLEN (Delly) and SVINSLEN (Manta). 
Can you please try it out?
Thanks
Fritz

**Comment by WEClarke** [comment]
Not sure what is wrong now. Here is the SVTYPE breakdown from the last run.

```
5738  SVTYPE=DEL
 774  SVTYPE=DUP
3773  SVTYPE=INS
 633  SVTYPE=INV
2471  SVTYPE=TRA
```
<br>
Here it is from this version.

```
   1  SVTYPE=DEL
 632  SVTYPE=INV
2470  SVTYPE=TRA
```

**Comment by fritzsedlazeck** [comment]
Ok that is me just submitting a small correction without testing. I will take care of this .
Thanks for reporting back.
Fritz

**Comment by fritzsedlazeck** [comment]
Done and tested. I changed the IF statements for the SVLen but I did not change the index for the parsing of the value. 
Thanks for reporting it.
Fritz

**Comment by WEClarke** [comment]
Resolved, thanks!

**Comment by Nazeeefa** [comment]
Hi,

Sorry if my question sounds silly, but just want to make sure - is SVLEN value in merged file correct representation of length of overlapping SVs?

Thanks,
Nazeefa

**Comment by fritzsedlazeck** [comment]
There are no silly questions, just bad documentation ;) 

The SVlen is the average length of all the events that got merged. The Start and Stop are chosen to be real coordinates. So if there are multiple we select the median start position as representative. 

I hope that helps
Fritz

**Comment by fritzsedlazeck** [comment]
oh and if the SVs is a DEL the SVlen is negative.
