### ISSUE TITLE
Merged calls: variants present in none of the samples 

### ISSUE THREAD

**Issue by CWYuan08** [fritzsedlazeck/SURVIVOR#85]
Dear Fritz, 

we have run survivor for merging Sniffles outputs of 21 samples. By checking the binary code representing the presence/absence of the SVs among the samples, there are rows that have all 0, which means that these SVs are not found in any strain, why this is? I have compared the first survivor combined output and the second run, the number of SVs got reduced, so what are these all 0 SVs? 

I have another question: how to correlate the SV in the combined file back to the individual vcf file at the beginning; for example if I select a SV in the individual file, and I want to know if it is present in other samples, how do I reliably identify it in the merged file? 
Thank you very much

Best
Ulrika

**Comment by fritzsedlazeck** [comment]
Hi Ulrika,
I should have made that clearer. I count them as 0 if the genotype is set to 0/0. There are unfortunately a lot of these ad hoc cases where I had to decide. I hope that does make sense. 

In the latest version of SURVIVOR we are tracking the variant ID from the original file in the genotype column. So you need to check which column your sample is and then check the variant ID. 

I hope that helps. Thanks for reaching out. 
Fritz

**Comment by CWYuan08** [comment]
@fritzsedlazeck Thank you for your quick response!
Regarding the first question: so if it is 0, it means no variant relative to the reference; if it is 1, it means the variant is present? so why do you report non-variants (i.e. not in any samples) in the final output?  

the second: What is the latest version? we used 1.0.5

Thank you again
Ulrika

**Comment by fritzsedlazeck** [comment]
Hi Ulrika,
If you check the output of Sniffles you should see that these variants are 0/0... the variant will still be reported. However, since its 0/0 because its e.g. low frequency in that sample I report it as a 0 in the SUPP_VEC. 

I think 1.0.5 has it included. 
Thanks
Fritz

**Comment by CWYuan08** [comment]
@fritzsedlazeck thanks, 
is it this: 
0/0:34:0
./.:0:0
0/1:2:1 
what does this mean? 

I will check the variant ID in Survivor outputs.
Ulrika

**Comment by fritzsedlazeck** [comment]
These are from one of the input files?
Or is that from the line that show all 0 in the support vector?

**Comment by CWYuan08** [comment]
Sorry, from the input files
I haven't correlate SVs in the input and the merged file.

**Comment by fritzsedlazeck** [comment]
Ok so this is a bit tricky... How do you merge?
SURVIVOR typically just takes the first column. Thus, it sees only the 0/0... 
Again sorry that this is so complicated but there are a lot of things that need to be taken into account...

**Comment by CWYuan08** [comment]
For merging: SURVIVOR merge {input} {wildcards.mergeDist} -1 1 -1 -1 -1 {output.vcfPop}
I had a look of the merged final output and I couldn't see the SV id in individual sample
example 1: 
chrI	3463	TRA003SUR	N	N[chrII:14567181[	.	PASS	SUPP=7;SUPP_VEC=001100100011000110000;AVGLEN=100000;SVTYPE=BND;SVMETHOD=SURVIVORv2;CHR2=chrII;END=14567181;CIPOS=0,0;CIEND=0,0;STRANDS=+-	GT:PSV:LN:DR:ST:TY:CO	0/0:NA:100000:2,0:+-:TRA:chrI_3463-chrII_14567181	0/0:NA:100000:1,0:+-:TRA:chrI_3463-chrII_14567181	1/1:NA:100000:2,26:+-:TRA:chrI_3463-chrII_14567181	./.:NA:100000:0,0:+-:TRA:chrI_3463-chrII_14567181	0/0:NA:100000:12,0:+-:TRA:chrI_3463-chrII_14567181	0/0:NA:100000:3,0:+-:TRA:chrI_3463-chrII_14567181	0/1:NA:100000:21,21:+-:TRA:chrI_3463-chrII_14567181	0/0:NA:100000:10,0:+-:TRA:chrI_3463-chrII_14567181	0/0:NA:100000:1,0:+-:TRA:chrI_3463-chrII_14567181	0/0:NA:100000:3,0:+-:TRA:chrI_3463-chrII_14567181	./.:NA:100000:0,0:+-:TRA:chrI_3463-chrII_14567181	./.:NA:100000:0,0:+-:TRA:chrI_3463-chrII_14567181	0/0:NA:100000:2,0:+-:TRA:chrI_3463-chrII_14567181	0/0:NA:100000:3,0:+-:TRA:chrI_3463-chrII_14567181	0/0:NA:100000:2,0:+-:TRA:chrI_3463-chrII_14567181	./.:NA:100000:0,0:+-:TRA:chrI_3463-chrII_14567181	./.:NA:100000:0,0:+-:TRA:chrI_3463-chrII_14567181	0/0:NA:100000:15,0:+-:TRA:chrI_3463-chrII_14567181	0/0:NA:100000:1,0:+-:TRA:chrI_3463-chrII_14567181	0/0:NA:100000:6,0:+-:TRA:chrI_3463-chrII_14567181	0/0:NA:100000:7,0:+-:TRA:chrI_3463-chrII_14567181

example2: 
chrI	8570	INS005SUR	N	<INS>	.	PASS	SUPP=11;SUPP_VEC=111000010011001010111;AVGLEN=43;SVTYPE=INS;SVMETHOD=SURVIVORv2;CHR2=chrI;END=8604;CIPOS=0,0;CIEND=0,0;STRANDS=+-	GT:PSV:LN:DR:ST:TY:CO	0/1:NA:43:15,17:+-:INS:chrI_8570-chrI_8604	0/1:NA:43:12,10:+-:INS:chrI_8570-chrI_8604	0/1:NA:43:36,17:+-:INS:chrI_8570-chrI_8604	0/0:NA:43:21,1:+-:INS:chrI_8570-chrI_8604	0/0:NA:43:12,4:+-:INS:chrI_8570-chrI_8604	0/0:NA:43:9,3:+-:INS:chrI_8570-chrI_8604	0/0:NA:43:21,5:+-:INS:chrI_8570-chrI_8604	0/1:NA:43:15,15:+-:INS:chrI_8570-chrI_8604	0/0:NA:43:12,2:+-:INS:chrI_8570-chrI_8604	0/0:NA:43:8,3:+-:INS:chrI_8570-chrI_8604	0/1:NA:43:4,6:+-:INS:chrI_8570-chrI_8604	0/1:NA:43:12,6:+-:INS:chrI_8570-chrI_8604	0/0:NA:43:35,13:+-:INS:chrI_8570-chrI_8604	0/0:NA:43:7,2:+-:INS:chrI_8570-chrI_8604	0/1:NA:43:4,9:+-:INS:chrI_8570-chrI_8604	0/0:NA:43:11,1:+-:INS:chrI_8570-chrI_8604	0/1:NA:43:9,4:+-:INS:chrI_8570-chrI_8604	0/0:NA:43:11,2:+-:INS:chrI_8570-chrI_8604	0/1:NA:43:16,13:+-:INS:chrI_8570-chrI_8604	0/1:NA:43:24,33:+-:INS:chrI_8570-chrI_8604	0/1:NA:43:20,46:+-:INS:chrI_8570-chrI_8604

**Comment by fritzsedlazeck** [comment]
I was more asking if you just merge all samples at once. Because on your previous example it looked like you did a premerge.. 
Thanks
Fritz

**Comment by CWYuan08** [comment]
Sorry, I can give you complete examples ( this time are definitely the raw vcf files): 
chrI	228982	0	N	TGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCGGGGGGGGTGGTTGGGGGGGGGGGGGGGGGGGGGGGGGTTTGTGTGGTTGTTTTGTTTTTTGGATGTGTGTTTTTTTGTTGTGTGTGTTTGGTGGGGGTTTTACTTTGGGTGGGTGGGGGGTGGGTCGGGGTTTTTTGTATGGTGGGGGGTTTGGGGGAGGGGGTTTGCGTGTTTGTTTTTTTGTTGGGGTTGGGGGGGTGGTTTGTGCGTTGGCCTGTGTGGTGGTGCATCTTTTTGGGGGTGGGGGTCTTTGGGTCTTGTTTGGTGTTGGGGTGGGTCTCGGGGGTCGTGTGGTGGGGTGTCTCGGGGGTTCCGTTGATGGTGTGGGTGGCTTTTTTGTCTTCTTTTTGTTGTTGGTGGGTGGGTTTTGGTGGGGTTCTGGGGTGGGGGAGGGGGGGTGTTAGTCGGTTCTTCGTTTAGTGTTCGTGGGGGGGGTGGGCGGTGGGGGCCTGGGGAGAGGGGGGGGGGGGCGGGGAGGGGGGGGGGTGTAGGTGTGCGTGGTGTGGTTGTTGTGGGGGGCGTGGCGAGGGGGGGGGCGGGGGGTGGGGGGGGGGGGGGGGGGGGGGTGGTTGGGGAGTGGGAGCCTGTGTGGTGGGGGGGGGTGGGGGGGCGGCGGGGGGGGGCGGCGTCGGGGGAGAGGGGGGTGACGGGGCGGGGGGGGGTTGTTGGGGGGCTGGGTGGAGGTGTTGGGTGTTAGGTGGATGGGTGGCGTTGGTGCGGGCGATGTGCTGCGTTGTTGCTGTGGGAGAGCTGGGGAGTGTGGGGGGGTCGGTCGGAGGGGGGTGGGGCTGAGTGGGTGGCGAGGTGTGGGGGGGGGTGTGTGGGTGGGGTGGTTGGTTGGGGTTCGTTTGGTTGTGGGGTTGGTGTGTGGGGTGGGTGGAGGTGGTGGGCGTGGTACTGTCGGGTTCGGTATGGGATGCTGGGTGGGGGTGGGGGTGGGGGGTGGTGAGGTGTGGGGTTGGTCTGGTTTGTGGGTGGTTTTTTGTTTTTGTGTGGTGATTGGTATCTTGTTTTTCTGTCTTTTTTTTGGTGTGGGATAGGCGGTGGGGGCGGGGCGTGGTTGGGGGTGGTGGTGATTGTTGGTTGTTTGGGAGGTGGGGGGGGGGGGGTGGGGGTGGCTGGGTGTTAGGGGTGATCGGTCTTTGGTTTTGTGGGGTTGTTTGTGGAGTTTCCGCGGTCGGGCTGGGGTGTGGGTGTTGCAATTTGCGGTTGGTGCGGGGTGCGTGTGTTTGAATGGTTGTTACGGGTGTCTTTTTGGAGTGCTGGGTCGTTGGTGTTGGTTGTCTGTGGTGTTGTGATCTTCGTTTGTTTTTTTTTTTTATTCTTTTTTTTGTTTTGGATTGTGGGTGTGGGGGTTTGTATTTTTGCGGGTGCGGGGGGGGGGGGGGGTTGAGGGGGGGGTTGTTGTTTTTTTGTGTGGGTCTGGGGGGGGGGTTTCGTTCTGGGCGCATCTGGCGGGTCGTATGCTGGTGTTGGGGGGGTTTTGCGGAGGGTGGCTCCGGTTTTGTGTTTTTGTGAGTGCGGTTTGGCTGGTGCGCGGTTGGTTGGTGGTGGTGGGGGGGGGGGGTGTGGGGGGGTGTCCGGTGGGTTGGTGCGTTTAGGTGTTGTTGTTTCGTTTGTGGTCGTGGGGTGGGTGCGGGGGGGG	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=chrI;END=229680;ZMW=13;STD_quant_start=10.620734;STD_quant_stop=289.450687;Kurtosis_quant_start=0.114299;Kurtosis_quant_stop=-0.807686;SVTYPE=INS;RNAMES=m54097_180218_083210/31129809/3154_22942,m54097_180218_083210/32179013/41156_58308,m54097_180218_083210/40567654/10650_55711,m54097_180218_083210/42467629/13340_36549,m54097_180218_083210/50135548/18663_28593,m54097_180218_083210/67371694/35326_41329,m54097_180218_083210/67698869/32270_49506,m54097_180218_083210/68682591/0_28670,m54097_180218_083210/7144224/17897_45808,m54097_180218_083210/73073543/0_16536,m54097_180218_184156/12714404/17685_22390,m54097_180218_184156/58327940/3349_11043,m54097_180218_184156/69993274/5265_24507;SUPTYPE=AL;SVLEN=678;STRANDS=+-;RE=13;REF_strand=19,30;AF=0.209677	GT:DR:DV	0/0:49:13
chrI	533097	1	N	TGGGGGTGTTAGTGGGGGGGGGTGTGTGGGGTCGGTGTTAGTGTGTTTGGGGGGGGTGGTGTGGGGGTGGGGTTTATGGTGTTGCGTTGGTTTGTTGTGGTGTTTTTCTTTTGTGGAGTGGGTTTGTGGTGGGGTTGTGTGTCTGGGGGT	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=chrI;END=533176;ZMW=18;STD_quant_start=6.449806;STD_quant_stop=17.383901;Kurtosis_quant_start=2.638895;Kurtosis_quant_stop=-0.552199;SVTYPE=INS;RNAMES=m54097_180218_083210/10027174/0_33158,m54097_180218_083210/13631874/33647_43924,m54097_180218_083210/17957131/18784_27357,m54097_180218_083210/54068165/3893_17430,m54097_180218_083210/60948850/355_15689,m54097_180218_083210/69403484/50832_69134,m54097_180218_184156/10027530/0_23302,m54097_180218_184156/12452531/0_9037,m54097_180218_184156/14484191/15496_29879,m54097_180218_184156/19005806/15759_30105,m54097_180218_184156/27525415/35379_42479,m54097_180218_184156/38142879/2140_22989,m54097_180218_184156/49349500/3813_7528,m54097_180218_184156/54788425/29498_43439,m54097_180218_184156/58852024/2828_16837,m54097_180218_184156/59703721/9025_26574,m54097_180218_184156/61407795/11477_22706,m54097_180218_184156/67503073/0_18184;SUPTYPE=AL,SR;SVLEN=79;STRANDS=+-;RE=18;REF_strand=34,28;AF=0.225	GT:DR:DV	0/0:62:18

**Comment by fritzsedlazeck** [comment]
ok makes sense. I was just worried that you input VCF file had multiple GT columns before the merge and that there was something going on that I dont understand. 

So here you have the 0/0 because only 18 out of 62 reads support that variant. Because AF=0.225 is the allele frequency and this is below the threshold.  

So when merging I wanted to distinguish if its present vs. low frequency. Thus I count the SUPP_VEC only if 1/1 or 0/1 if GT are given.  This can for sure discussed, but this is how its is currently implemented...

Does that explain it?
Cheers
Fritz

**Comment by CWYuan08** [comment]
I see, thanks. Some of them has ./. what does this mean? 
Did you see the Survivor examples above, I couldn't see the SV ID name in individual samples, is this the format you would expect?

**Comment by fritzsedlazeck** [comment]
./. is undefined. That can happen if it falls under certain coverage..
Can you send me a part of the merged file? Its always hard for me to decipher that based on copy paste in github. :)
email: fritz.sedlazeck@gmail.com

**Comment by CWYuan08** [comment]
@fritzsedlazeck , sure no problem, I have sent you an example file

**Comment by fritzsedlazeck** [comment]
got it. No its not included. 
You can see that in the header:
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=LN,Number=1,Type=Integer,Description="predicted length">
##FORMAT=<ID=DR,Number=1,Type=Integer,Description="# supporting reference,variant reads in that order">
##FORMAT=<ID=ST,Number=1,Type=String,Description="Strand of SVs">
##FORMAT=<ID=TY,Number=1,Type=String,Description="Types">
##FORMAT=<ID=CO,Number=1,Type=String,Description="Coordinates">
##FORMAT=<ID=PSV,Number=1,Type=String,Description="Previous support vector">


The best is if you clone the newest code and use that. 
Cheers
Fritz

**Comment by CWYuan08** [comment]
Thank you for being so helpful! @fritzsedlazeck 
I will rerun Survivor
Best regards
Ulrika

**Comment by CWYuan08** [comment]
Hi @fritzsedlazeck,
we have rerun the analysis with the newest version of Survivor. I am wondering how should I properly load this information in R: 
 ##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=PSV,Number=1,Type=String,Description="Previous support vector">
##FORMAT=<ID=LN,Number=1,Type=Integer,Description="predicted length">
##FORMAT=<ID=DR,Number=2,Type=Integer,Description="# supporting reference,variant reads in that order">
##FORMAT=<ID=ST,Number=1,Type=String,Description="Strand of SVs">
##FORMAT=<ID=QV,Number=1,Type=String,Description="Quality values: if not defined a . otherwise the reported value.">
##FORMAT=<ID=TY,Number=1,Type=String,Description="Types">
##FORMAT=<ID=ID,Number=1,Type=String,Description="Variant ID from input.">
##FORMAT=<ID=RAL,Number=1,Type=String,Description="Reference allele sequence reported from input.">
##FORMAT=<ID=AAL,Number=1,Type=String,Description="Alternative allele sequence reported from input.">
##FORMAT=<ID=CO,Number=1,Type=String,Description="Coordinates">

I tried with vcfR and got: "Extracting gt element GT
Error in extract.gt(x = vcf, element = format_fields[i], as.numeric = coerce_numeric[i]) : 
  ID column contains non-unique names"

Thank you again 
with regards
Ulrika

**Comment by fritzsedlazeck** [comment]
Hi Ulrika,
The vcf should be standard confirm. The IDs however might not because I take the IDs from the previous files. 
The header entries that you posted are normal.
I usually don't use R so I am not familiar with that package. What do you want to do?

Cheers
Fritz

**Comment by CWYuan08** [comment]
Dear @fritzsedlazeck,
thank you for replying. 
if not in R , how do you normally parse the Format columns of each sample? 

I am analysing the SV vcf files of a list of strains of our model organism; I don't quite understand what you meant by the following: (which is after first Survivor, on the population variant calling page of Sniffles). 
"This will generate one VCF file for all the samples, but we lack the information if a SV identified in one sample but not in the other is really absent."

So after the first Survivor, nearby SVs within individual samples have been merged; what is the aim of second run of Sniffles and Survivor? Could I just run Survivor once, and use the output for finding shared calls? 

Thank you 
With regards 
Ulrika

**Comment by fritzsedlazeck** [comment]
Hi Ulrika,
yes you could just use the first SURVIVOR merge. I usually use like the command line and adopt this to parse certain flags from the INFO field:
`perl -ne 'print "$1\n" if /RE=([^,;]+)/' my.vcf  `

I hope that helps.

to your question about why a second run with Sniffles. So it can be that because of thresholds/ low coverage or whatever reason a SV was missed. So Sniffles has a beta version mode to force call these SVs. So you could use the SURVIVOR merge output to make sure that these variants are indeed not present in the other samples. 

Does that explains it?
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
I am closing this issue. Please let me know if I forgot to reply to a certain point.
