### ISSUE TITLE
Will survivor merge two calls if they have different genotyping? 

### ISSUE THREAD

**Issue by cagaser** [fritzsedlazeck/SURVIVOR#86]
Hi Fritz, 

I was just wondering wether SURVIVOR will merge two similar calls but with different genotyping, say one is hom. 1/1 and the other is het. 0/1

Thank you in advance, 

Cedrick

**Comment by fritzsedlazeck** [comment]
Yes. It does not care about the genotype difference. 
Cheers
Fritz
