### ISSUE TITLE
Finding CNVs that do not intersect/merge with reference set

### ISSUE THREAD

**Issue by ggstatgen** [fritzsedlazeck/SURVIVOR#87]
Hi

I've been using SURVIVOR to merge sets of SVs (i.e. compute the intersection).

Now I have a slightly different problem. Given 2 sets of SVs, say set A (study) and set B (reference), I would like to compute the set C=A-B. That is I'd like to find all SVs that are novel in A.

Can Survivor be used for this purpose? At the moment, my (imperfect) strategy is as follows

1. Survivor(A,B) -> merged set (ie A-intersect-B)
2. bedtools intersect -v -a A -b (A-intersect-B)

Which is of course sub-par for several reasons (bedtools doesn't know if an interval is a deletion or insertion, for starters)

**Comment by fritzsedlazeck** [comment]
Sure. What I usually do is to merge as normal.
then look at the SUPP_VEC= . Identify the pattern that matches your query. E.g. first sample = A, second sample =B you want to grep 'SUPP_VEC=10;' or something similar. 
Cheers
Fritz

**Comment by ggstatgen** [comment]
Thanks Fritz! Worked fine when filtering for ''SUPP_VEC=01'.
