### ISSUE TITLE
SURVIVOR merging to wrong svtypes.

### ISSUE THREAD

**Issue by unique379r** [fritzsedlazeck/SURVIVOR#88]
Hi Again,

I running lattes version (1.0.7) of SURVIVOR and found strange behavior of merging, though i am using svtype into consideration. 

list:
BreakDancerSortVCF.vcf
dellySort.vcf
lumpySort.vcf
MantaCandidateSV..vcf.gz

##OPTIONS
Caller = 3
Type
No minimum sv length
No strand info

```
SURVIVOR merge list 1000 3 1 0 0 30 MergeOut.vcf

chr15	78630477	MantaINS~364025~1~2~0~0~0	TG	TTTGGTGTACCACCCAGAGACCACAGAGACAGTTGGATGCCATTCTTCACTCACTGAAGTAGAGAAATGTATGTATA	.	PASS	SUPP=3;SUPP_VEC=0111;SVLEN=585;SVTYPE=DUP;SVMETHOD=SURVIVOR1.0.7;CHR2=chr15;END=78631125;CIPOS=0,621;CIEND=-27,0;STRANDS=+-	GT:PSV:LN:DR:ST:QV:TY:ID:RAL:AAL:CO	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	0/1:NA:554:18,0:-+:.:DUP:DUP00014037:NA:NA:chr15_78630545-chr15_78631099	./.:NA:554:0,32:+-:.,.:DUP,DEL:27945:NA:NA:chr15_78630544-chr15_78631098,chr15_78630605-chr15_78631099	./.:NA:648:0,0:+-:.,.,.:DUP,INS,INS:MantaINS~364025~1~2~0~0~0:TG:TTTGGTGTACCACCCAGAGACCACAGAGACAGTTGGATGCCATTCTTCACTCACTGAAGTAGAGAAATGTATGTATA:chr15_78630477-chr15_78631125,chr15_78631098-chr15_78631099,chr15_78631098-chr15_78631099
```

You may see SURVIVOR took call of DUP and DEL from "delly" as well as "DUP", "INS", "INS", "INS" from Manta.

I really dont get it, since INS in both case have either one base difference or none (start and end is same in case of manta). It should NOT merge INS. 

```
Example of DEL in all four vcf (random not the above example):

MantaCandidateSV.vcf
chr1	3009350	MantaDEL:7:0:0:0:0:0	TTGTGTGTGTGTG	T	.	.	END=3009362;SVTYPE=DEL;SVLEN=-12;CIGAR=1M12D;CIPOS=0,41;HOMLEN=41;HOMSEQ=TGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGT;UPSTREAM_PAIR_COUNT=0;DOWNSTREAM_PAIR_COUNT=0;PAIR_COUNT=0

GT190533_FKDL190729564-1a_H225YCCX2_cat_L2_1.fq.gz_dedupe_BreakDancerSortVCF.vcf
chr1	3499556	.	.	.	.	PASS	PROGRAM=breakdancer;SVTYPE=DEL;SVLEN=2855;SVEND=3502300	GT:DP	1/.:16

GT190533_FKDL190729564-1a_H225YCCX2_cat_L2_1.fq.gz_dedupe_dellySort.vcf
chr1	3031359	DEL00000000	T	<DEL>	0	PASS	PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv0.8.1;CHR2=chr1;END=3031717;PE=0;MAPQ=0;CT=3to5;CIPOS=-8,8;CIEND=-8,8;SRMAPQ=60;INSLEN=0;HOMLEN=7;SR=16;SRQ=0.994845;CONSENSUS=CATGCTCTATACCTAATACCCACTTATCAGTGAGTATACACCATGTGTGATATTTTGTGATGGAGTTACCTCACTCAGGATATTATTTTGTAGATCCATTCATTTGCCTGTGAGTTTCATGAAGTCACTATTTTTAATAGCTGAGTAATACTCCATTTTGTAAATATATCAGATTTTCTGTATCTATTCCTCT;CE=1.89153	GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV	1/1:-103.199,-7.82553,0:78:PASS:5534:22:5773:0:0:0:0:26

GT190533_FKDL190729564-1a_H225YCCX2_cat_L2_1.fq.gz_dedupe_lumpySort.vcf
chr1	3031359	1	N	<DEL>	.	.	SVTYPE=DEL;STRANDS=+-:19;SVLEN=-359;END=3031718;CIPOS=0,0;CIEND=0,0;CIPOS95=0,0;CIEND95=0,0;SU=19;PE=0;SR=19	GT:SU:PE:SR	./.:19:0:19
```

You may notice that there is no SVLEN for Delly whereas lumpy and manta have negative SVLEN while breakdancer have +ve SVLEN. 
is that make confusion to SURVIVOR ?

Regards,
Rupesh

**Comment by fritzsedlazeck** [comment]
Hi Rupesh,
for within sample merging, we do not take into account the typesafe or other parameters. 

So you see they got merged across the samples because there is the dup in there as the leading type, but then INS are just overlapping with the DUP within the calls. 

Does that make sense?
Thanks
Fritz

**Comment by unique379r** [comment]
Hi Fritz

You mean I should not use SVTYPE (fourth parameter i.e. 1) ?

If yes, then i tried again without using it but still call is same as above.

```
SURVIVOR merge list 1000 3 0 0 0 30 MergeOut.vcf

chr15	78630477	MantaINS~364025~1~2~0~0~0	TG	TTTGGTGTACCACCCAGAGACCACAGAGACAGTTGGATGCCATTCTTCACTCACTGAAGTAGAGAAATGTATGTATA	.	PASS	SUPP=3;SUPP_VEC=0111;SVLEN=585;SVTYPE=DUP;SVMETHOD=SURVIVOR1.0.7;CHR2=chr15;END=78631125;CIPOS=0,621;CIEND=-27,0;STRANDS=+-	GT:PSV:LN:DR:ST:QV:TY:ID:RAL:AAL:CO	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	0/1:NA:554:18,0:-+:.:DUP:DUP00014037:NA:NA:chr15_78630545-chr15_78631099	./.:NA:554:0,32:+-:.,.:DUP,DEL:27945:NA:NA:chr15_78630544-chr15_78631098,chr15_78630605-chr15_78631099	./.:NA:648:0,0:+-:.,.,.:DUP,INS,INS:MantaINS~364025~1~2~0~0~0:TG:TTTGGTGTACCACCCAGAGACCACAGAGACAGTTGGATGCCATTCTTCACTCACTGAAGTAGAGAAATGTATGTATA:chr15_78630477-chr15_78631125,chr15_78631098-chr15_78631099,chr15_78631098-chr15_78631099

```

**Comment by fritzsedlazeck** [comment]
Hi,
no what I mean for the merge within one input vcf (e.g. the dup , ins, ins) I did not implement any check because if they are merged its very likely to be indeed the same event. At least that was my logic back then. The DUP/ DEL is a bit strange... but DUP/ INS can make sense. 

For the among sample/ multi VCF merge it looks valid because everyone has a DUP that got merged. 

Does that make sense?
Thanks
Fritz

**Comment by unique379r** [comment]
Ok, but i concern about DEL.
So what i think is better and safe to do is to split the vcf by svtype and then use SURVIVOR to merge it.

Rupesh

**Comment by fritzsedlazeck** [comment]
By that, you can avoid this. 
It would be interesting to go back to the input and see what is going on at this region. I have seen ins vs. DUP calls but never DEL vs. DUP calls on the same region... 

Could you let me know what you find?
Thanks
Fritz

**Comment by unique379r** [comment]
Hi Fritz
After this strange behaviors of SURVIVOR, I went back check my previous analysis with only three tools (breakdancer (1) , delly (2) and lumpy(3)) and found it is also happening with DUP+INV and DEL+INV by delly and lumpy.

```
For example: DEL+INV 

[chr2:98662691[N ./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN 1/1:NA:488:8380,0:--:.:INV:INV00019944:NA:NA:chr2_98662232-chr2_98662720 ./.:NA:273:0,7:++:.,.,.,.,.,.:INV,INV,DEL,INV,INV,INV:700_2:NA:NA:chr2_98662501-chr2_98662691,chr2_98662547-chr2_98662820,chr2_98662551-chr2_98662720,chr2_98662660-chr2_98662733,chr2_98662691-chr2_98662501,chr2_98662820-chr2_98662547
```

```
Delly original call:

chr2	98662232	INV00019944	C	<INV>	.	PASS	IMPRECISE;SVTYPE=INV;SVMETHOD=EMBL.DELLYv0.7.8;CHR2=chr2;END=98662720;PE=180;MAPQ=44;CT=5to5;CIPOS=-50,50;CIEND=-50,50	GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV	1/1:-1000,-738.184,0:10000:PASS:816:10587904:3307047:6:482:7898:0:0

lumpy original call:

chr2	98662551	697	N	<DEL>	.	.	SVTYPE=DEL;STRANDS=+-:4;SVLEN=-169;END=98662720;CIPOS=0,0;CIEND=0,0;CIPOS95=0,1;CIEND95=0,2;IMPRECISE;SU=4;PE=0;SR=4	GT:SU:PE:SR./.:4:0:4

chr2	98662547	700_1	N	N]chr2:98662820]	.	.	SVTYPE=BND;STRANDS=++:7;EVENT=700;MATEID=700_2;CIPOS=0,0;CIEND=0,0;CIPOS95=-3,1;CIEND95=-1,2;IMPRECISE;SU=7;PE=1;SR=6	GT:SU:PE:SR	./.:7:1:6
chr2	98662820	700_2	N	N]chr2:98662547]	.	.	SVTYPE=BND;STRANDS=++:7;SECONDARY;EVENT=700;MATEID=700_1;CIPOS=0,0;CIEND=0,0;CIPOS95=-1,2;CIEND95=-3,1;IMPRECISE;SU=7;PE=1;SR=6	GT:SU:PE:SR	./.:7:1:6

chr2	98662501	6945_1	N	[chr2:98662691[N	.	.	SVTYPE=BND;STRANDS=--:4;EVENT=6945;MATEID=6945_2;CIPOS=0,0;CIEND=0,0;CIPOS95=-1491,0;CIEND95=-84,0;IMPRECISE;SU=4;PE=4;SR=0	GT:SU:PE:SR	./.:4:4:0
chr2	98662691	6945_2	N	[chr2:98662501[N	.	.	SVTYPE=BND;STRANDS=--:4;SECONDARY;EVENT=6945;MATEID=6945_1;CIPOS=0,0;CIEND=0,0;CIPOS95=-84,0;CIEND95=-1491,0;IMPRECISE;SU=4;PE=4;SR=0	GT:SU:PE:SR	./.:4:4:0

```

You can see, all of these calls are very close to each other, and i guess it is a lowQUAL calls with lower supports or artifacts ? SURVIVOR take this BND as INV type. Lumpy never have INFO field as lowQAUL or PASS. 

any explanation ?

Rupesh

**Comment by fritzsedlazeck** [comment]
Hi Rupesh,
yes BND are generally viewed as INV if both breakpoints are on the same chromosome. 
And as I explained before the within input vcf merge groups these together since the coordinates are close. Is that what you are pointing to?

Thanks
Fritz

**Comment by unique379r** [comment]
Yes Fritz, when BND is on different chromosomes then it becomes TRA otherwise its a INV. 
I was just want to make sure that if SURVIVOR merges calls correctly with same svtypes. But it is not the case, not always !! So my question is that is it normal if majority is DUP and it merges with INV ? or INV with DEL? or some other cases like mixture of ? I hope its not a bug on SURVIVOR.

**Comment by fritzsedlazeck** [comment]
I see. thanks for replying that fast. 

So yes it merged events if they are provided in the same VCF together independent of the event. 
For merges between input VCF files it depends on the parameter that you choose. 

So in the above example, the Lumpy calls are merged together because of their closeness to the breakpoints. And then they are merged together with the Delly calls since they are overlapping and support the same type of SV. 

Does that make sense? Or do you think I should not allow the merge within the input VCF to be non type specific?
Thanks
Fritz

**Comment by unique379r** [comment]
Thanks Fritz for your explanations. For me SVTYPE should be consistent otherwise it looks suspecius that calls are specific SVTYPE if its mixes. For me BND tags left as it is, when program is not sure what kind of SVtype it is. It could be by many factors such as low Quality calls/Low supports/artifacts/repetitive regions etc.
Now. its up to you as you have more experience (technically as well as biologically) than me for sure, to judge is this a problem or normal behavior in terms of biology or computationally. 

Technically i could think of splitting by types and merge it to avoid this issue. This is what i could think of now.

Rupesh

**Comment by fritzsedlazeck** [comment]
Hi Rupesh,
well frankly no one knows. 

Here is my logic: If events are called on top of each other it was most of the time some error in at least one of the calls. Eg. you sometimes saw Ins + DUP occurring. This was the reasoning why I am merging the calls together if they are in the same input VCF file. This usually also does not occur too often. 
I am a bit reluctant to change this behavior from Sniffles because I saw that too often that events overlapping in one sample are echos.. However, as I said no one knows... So please feel free to split before the merge and sorry for the hussle. 

BND are not called because of low quality!  According to the standard its a replacement for TRA and can also replace other SV types. Some callers only provide BND calls (I think Grids is one of them). 

Thanks for the insights and please keep me posted. 
Fritz

**Comment by unique379r** [comment]
HI Fritz,
Thank you for your explanation. With the chain of thought, i was thinking to categorize it as a COMPLEX event type (a mixture of svtypes), may i ??

```
Example: Here we found a mixture of events (DUP,DEL and INS) have been merged on top of DUP. So it can be categorized as COMPLEX event !! NO?

chr13	76211782	MantaINS~21296~3~3~0~0~0	TG	TCTTGGACACTTTATTTTCTATGGTCTTCACTTTATTTACTTTTGCCTCCTGTTTCTGGGAGTTCATAAAATTCTCCAACTTGCTTGAAAGT	.	PASS	SUPP=3;SUPP_VEC=0111;SVLEN=493;SVTYPE=DUP;SVMETHOD=SURVIVOR1.0.7;CHR2=chr13;END=76212346;CIPOS=0,542;CIEND=-22,0;STRANDS=+-	GT:PSV:LN:DR:ST:QV:TY:ID:RAL:AAL:CO	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	0/1:NA:458:23,0:-+:.:DUP:DUP00012569:NA:NA:chr13_76211867-chr13_76212325	./.:NA:458:0,21:+-:.,.:DUP,DEL:23785:NA:NA:chr13_76211866-chr13_76212324,chr13_76211961-chr13_76212325	./.:NA:564:0,0:+-:.,.,.:DUP,DEL,INS:MantaINS~21296~3~3~0~0~0:TG:TCTTGGACACTTTATTTTCTATGGTCTTCACTTTATTTACTTTTGCCTCCTGTTTCTGGGAGTTCATAAAATTCTCCAACTTGCTTGAAAGT:chr13_76211782-chr13_76212346,chr13_76211959-chr13_76212325,chr13_76212324-chr13_76212325

```
What do you think ?

**Comment by unique379r** [comment]
Seeing above output, now i have another doubts to use size of sv (a option of SURVIVOR).

For example when i used size 0 (intended to have INS), so yeah i have some SVTYPE=INS along with some of them have merged as COMPLEX event type.

```
SURVIVOR merge sample 1000 3 1 0 0 0 BDLM.0size.vcf

merging entries: 9934
merging entries: 18179
merging entries: 54017
merging entries: 436757

But when i used size 30bp (min size of sc to be considered) then why SURVIVOR takes INS to merge it with other SVTYPE (complex event) as we have seen before.

SURVIVOR merge sample 1000 3 1 0 0 30 BDLM.30size.vcf

merging entries: 9909
merging entries: 10517
merging entries: 50906
merging entries: 111649

chr13	76211782	MantaINS~21296~3~3~0~0~0	TG	TCTTGGACACTTTATTTTCTATGGTCTTCACTTTATTTACTTTTGCCTCCTGTTTCTGGGAGTTCATAAAATTCTCCAACTTGCTTGAAAGT	.	PASS	SUPP=3;SUPP_VEC=0111;SVLEN=493;SVTYPE=DUP;SVMETHOD=SURVIVOR1.0.7;CHR2=chr13;END=76212346;CIPOS=0,542;CIEND=-22,0;STRANDS=+-	GT:PSV:LN:DR:ST:QV:TY:ID:RAL:AAL:CO	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	0/1:NA:458:23,0:-+:.:DUP:DUP00012569:NA:NA:chr13_76211867-chr13_76212325	./.:NA:458:0,21:+-:.,.:DUP,DEL:23785:NA:NA:chr13_76211866-chr13_76212324,chr13_76211961-chr13_76212325	./.:NA:564:0,0:+-:.,.,.:DUP,DEL,INS:MantaINS~21296~3~3~0~0~0:TG:TCTTGGACACTTTATTTTCTATGGTCTTCACTTTATTTACTTTTGCCTCCTGTTTCTGGGAGTTCATAAAATTCTCCAACTTGCTTGAAAGT:chr13_76211782-chr13_76212346,chr13_76211959-chr13_76212325,chr13_76212324-chr13_76212325

In my opinion it should be dropped as INS in all callers have either length of 1 or 0 (considering start and end is same). 
```

What is your explanation ?

**Comment by fritzsedlazeck** [comment]
INS do have a size and its taken into account. 
Manta is calling 3 different type of events on top of each other. That is suspicious. 
SURVIVOR does not assign a flag complex to any of the variants (if that is what you are asking).

**Comment by unique379r** [comment]
Thanks fritz,
Yeah i get it. Some INS have svlength and some have only 0 or 1. so are you taking length information directly from INFO field of each vcf? If yes then some callers have DEL as negative length or some have positive, so it can be problematic to merge.

By the way ...complex event was my idea, I know SURVIOR is not assigning anything like that. Sorry if i wasn't clear.

Rupesh

**Comment by fritzsedlazeck** [comment]
Yes its a bit complicated. So I take it from the info field or from the sequence if its present in the alt column. The length for DEL is taken as positive. I also use the Start/ End coordinates as indications if the length is undefined. 

No problem. Its not a bad idea. :) Just wanted to make sure. Answering most of these questions here during calls etc. So I am not always 100% on top of things :). 
Thanks
Fritz
