### ISSUE TITLE
Venn

### ISSUE THREAD

**Issue by biomichal** [fritzsedlazeck/SURVIVOR#89]
Hi, Fritz, 
I noticed in the Wiki part of SURVIVOR "Note that SURVIVOR will produce further a venn diagram file that will not be filtered by the min. number of supporting callers and can be used to visualize the results".
But I can not find the script to generate the venn diagram.

**Comment by fritzsedlazeck** [comment]
Yes that was in a much older version. The easiest way to obtain something like this is to extract the SUP_VEC= information and use that to produce a venn diagram. 

I will need to update the wiki, but as you probably know there are so many more important things.. unfortunately. 
Sorry for the confusion. 
Fritz

**Comment by Nazeeefa** [comment]
Hi,

Has anyone tried what you suggested above? I'd like to give it a go but just wondering whether it worked if anyone else has done it? or is any extra information required? :) Thanks!

Cheers,
Nazeefa

**Comment by fritzsedlazeck** [comment]
Hi Nazeefa,
I have updated SURVIVOR a bit. so you can now take your merged vcf file and put it into SURVIVOR genComp . You will get a pairwise distance matrix out. 
Next you can use an R heatmap to plot this. 
For example:
readin the matrix to e.g. t

dst <- data.matrix(t(t))
image(1:nrow(dst), 1:ncol(dst),log(dst), col=rev(heat.colors(10)),axes=F, xlab="", ylab="")
grid(col='black',nx=nrow(dst),ny=ncol(dst),lty=1)

I hope that helps.
Fritz

**Comment by fritzsedlazeck** [comment]
I included a short description in the wiki. 
https://github.com/fritzsedlazeck/SURVIVOR/wiki#plotting-the-comparison-of-multiple-input-vcf-files-after-merging
I hope that helps.
Fritz

**Comment by Nazeeefa** [comment]
Hi Fritz,

Thank you. I had a look at the instructions. I have <5 vcf files. I couldn't extract information using the perl command. Instead, I used:
```
bcftools query -f '%CHROM[\t%INFO/SUPP_VEC]\n' merged.vcf | awk '{ for(i=2; i<=NF; i++) {printf("%s\t", $i)} print $NF } | (sed command) > out.vcf
```
However, I can't seem to get venn diagram - here's the code:
`venn.diagram(list(sample1=which(t[,1]==1), sample2=which(t[,2]==1), sample3=which(t[,3]==1), sample4=which(t[,4]==1)) , fill = c("red", "orange" ,"blue", "green") , alpha = c(0.5, 0.5, 0.5, 0.5), cex = 2, lty =2, filename = "overlap.tiff")`

Sorry if it seems silly, it gives an error saying "_Error in t[, 1] : object of type 'closure' is not subsettable._"
 
Thanks again, I appreciate your time!

Cheers,
Nazeefa

**Comment by fritzsedlazeck** [comment]
1. Do you know why you didn't get anything from the Perl one liner?
2. Please paste the head of your output file

3. How did you read in your output file in R?
Cheers
Fritz

**Comment by Nazeeefa** [comment]
1. Yes, because it's missing $1 in `print "\n"`
2. From fixed Perl one-liner, I get the following:
```
0 0 1 0 
0 1 1 1 
0 0 1 1 
```
3. t <- read.table("overlap.txt")

It seems to work.

Cheers,
Nazeefa

**Comment by fritzsedlazeck** [comment]
Thanks. I updated the wiki.

So everything seems to work now?
Thanks
Fritz

**Comment by Nazeeefa** [comment]
Yes, thanks Fritz :) I appreciate your time!

except, and this is probably a different issue (apologies), information from this NA12878 vcf file (ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/NA12878/NA12878_PacBio_MtSinai/) doesn't seem to be used for output when I run `merge` - just interesting in finding overlap between truth set and vcf files I have.

**Comment by fritzsedlazeck** [comment]
What information exactly? 
As you know VCF files can quite vary in the way the report information and what information they report. 
Thus, SURVIVOR filters out the necessary information to provide the merge, but dont carry over all the genotypes or frequencies.. 
Thanks
Fritz

**Comment by Nazeeefa** [comment]
Hi Fritz,

Overlapping information (SUPP_VEC tags). What I was trying to understand if Survivor supports the output format* of the _NA12878_PacBio_ vcf file. 

I decided to use callsets, available [here](https://www.ncbi.nlm.nih.gov/dbvar/studies/nstd152/#samplesetsTab), for truth set. When I extract information for overlapping variants, it shows that there is no overlap between truth set and my dataset. I'm wondering if there's something missing from truth set file that contributes to this. I know that a list of "contigs" (chromosome names and their length) is missing from header, but not sure if that's the reason.

Thank you for all the help and time so far! I really appreciate it :)

Cheers,
Nazeefa
