### ISSUE TITLE
Assemblytics to VCF with SV name leftover

### ISSUE THREAD

**Issue by RenzoTale88** [fritzsedlazeck/SURVIVOR#90]
Hello,
I need to convert SV from an Assemblytics output to VCF. However, I noticed that the software changes the variant IDs. Is there a way to lift over the variant names as well? Or at least, is there a way to associate the two files, so to know which is each variant?

Thank you in advance,

Andrea

**Comment by fritzsedlazeck** [comment]
Sure that is easy to extend. I dont have an Assemblytics file at hand right now. Can you send me one: fritz.sedlazeck@gmail.com 
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Hi I adopted the code. 
please clone and try it again. Just watch out your file was formatted in a way that the separation was in space not in tab...  Maybe that happened on my side, but I wanted to let you know.
Cheers
Fritz

**Comment by RenzoTale88** [comment]
It works, thank you very much!!
