### ISSUE TITLE
SURVIVOR wrong merge

### ISSUE THREAD

**Issue by Litterlemon** [fritzsedlazeck/SURVIVOR#91]
hello，
some records going wrong when i use SURVIVOR to merge some vcf. Such as:
`
19	39898269	DEL001617805SUR	N	<DEL>	.	PASS	SUPP=1;SUPP_VEC=01;AVGLEN=1075;SVTYPE=DEL;SVMETHOD=SURVIVORv2;CHR2=19;END=39898388;CIPOS=-956,0;CIEND=-956,0;STRANDS=+-	GT:PSV:LN:DR:ST:TY:CO	./.:NaN:0:0,0:--:NaN:NaN	0/1:NA:1075:0,2:+-:DEL,DEL:19_39898269-19_39898388,19_39897313-19_39898388
`

19_39897313-19_39898388 is not exist in  original vcf,but is 

`
20	39897313	1089548	N	<DEL>	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.8;CHR2=20;END=39898388;STD_quant_start=0.000000;...
`

**Comment by fritzsedlazeck** [comment]
Hi,
Thanks for reaching out. I don't quite understand the problem. The entry is exactly what you showed. It summarizes the start and the end coordinate with it's chromosome for both breakpoints. 
So I don't see the problem. 
Thanks
Fritz

**Comment by Litterlemon** [comment]
hi,Fritz
i don't understand why different chromosome were merged together.

**Comment by fritzsedlazeck** [comment]
Can you send me that VCF file? fritz.sedlazeck@gmail.com
And please let me know what version of SURVIVOR you are using.
Thanks
Fritz
