### ISSUE TITLE
SURVIVOR with paragraph

### ISSUE THREAD

**Issue by KamilSJaron** [fritzsedlazeck/SURVIVOR#93]
Hello Fritz,

I was wondering. Have you tried to plug merged calls from SURVIVOR as candidate SVs to for paragraph?

The strategy of SV calling used to build candidates that subsequentially genotyped is already proposed by [Delly](https://github.com/dellytools/delly#germline-sv-calling) or [smoove](https://github.com/brentp/smoove). I really like the idea, but I think it would be nice if it would be detached from one particular SV caller.

I actually tried this already, but I used a too old version of SURVIVOR (1.0.2) and run in some problems with headers (which seems to be fixed in 1.0.3). But I thought I ask you anyway what do you think about SURVIVOR + paragraph combo.

**Comment by fritzsedlazeck** [comment]
Hey,
yeah the problem I see is more about the sequence representation. SURIVOR can move the sequences over from the input, but depending on the caller this will work or not. 

In general, I havent tested SURVIVOR with Paragraph now.. We only used the Sniffles calls based on CCS Pacbio reads. 

Cheers
Fritz

**Comment by KamilSJaron** [comment]
Ha, good to know. Perhaps it would be sufficient to provide a list of "nicely behaving callers" that could be used for paragraph. 

Unfortunately, we don't have the luxury of long reads. Right now, we have lumpy, delly and manta calls. I will check when I can do with it.

Cheers

**Comment by fritzsedlazeck** [comment]
Yeah Manta should behave nicely. Brend tested lumpy and these were too inaccurate.. plus I am not sure what he did because I dont think lumpy produces sequence resolved SV..

You can also check out STIX another method that I am involved in. Works quite well.  Let me know if you want to have a quick call.. 

Cheers
Fritz

**Comment by KamilSJaron** [comment]
Sweet. I will take a look.

I have a really cool dataset of 10 species + 50 reseq individuals (i.e. 6 individuals per species, single genus) and I already get really nice population genomics results with raw SV calls of manta. I just wanted to get a more convincing approach to support the observed patterns and perhaps improve a bit better signal to noise ratio.

This being said, I am handing my thesis in less than two weeks, so I am a bit preoccupied with writing by now. After that, however, I will certainly jump on finishing up the SV analysis for a paper, then maybe having a chat with the SV guru would be helpful :-).

**Comment by fritzsedlazeck** [comment]
Sounds cool. Good luck. Just ping me...
I will close this issue now. 
Cheers
Fritz
