### ISSUE TITLE
Multiple samples in one VCF

### ISSUE THREAD

**Issue by alexmathieu** [fritzsedlazeck/SURVIVOR#95]
Hi,

I have two VCFs, one with Lumpy and one with Wham.
In each vcf I have 23 samples. When I merge the two VCF with SURVIVOR, I have an output VCF but there is only one sample.

What is the best way to merge the two VCFs ?

Thanks per advance,

Alexandre

**Comment by fritzsedlazeck** [comment]
Hi Alexandre,

sorry its not intended like this. So SURVIVOR would need to be run first on the two callers per sample. Then merging the 23 merged vcf files to one.

Thanks
Fritz

**Comment by alexmathieu** [comment]
Thank You for your answer !!!

**Comment by danrlu** [comment]
This is quite useful information that may be worth including on the wiki for SV newbie like myself. 
Thanks for building such a useful tool!!
